### PR TITLE
Fix minor issues

### LINKED ISSUE #483: 5.3.0 preview crashes on main menu
After trying current preview version of 5.3.0 my game crashes when main menu is about to be displayed.
No such problem with 5.2.0 release.

Cleo.log:
```
09/01/2026 19:04:21.066 
09/01/2026 19:04:21.066 Log started.
09/01/2026 19:04:21.066 CLEO v5.3.0-1129e9b
09/01/2026 19:04:21.066 
09/01/2026 19:04:21.066 Opening memory access...
09/01/2026 19:04:21.066  Unprotecting memory region '.text': 0x00001000 (size: 0x00456000)
09/01/2026 19:04:21.066  Unprotecting memory region '.rdata': 0x00458000 (size: 0x0004C000)
09/01/2026 19:04:21.066  Unprotecting memory region '.text': 0x008B1000 (size: 0x0064A000)
09/01/2026 19:04:21.066 
09/01/2026 19:04:21.066 Started on game of version: SA 1.0 us
09/01/2026 19:04:21.066 CLEO initialization: Phase 1
09/01/2026 19:04:21.086 Commands database version 1.40 loaded from 'D:\GTA_SA\cleo\.config\sa.json'
09/01/2026 19:04:21.086 Injecting MenuStatusNotifier...
09/01/2026 19:04:21.086 Replaced call at: 0x0057B9FD, original function was: 0x00728350
09/01/2026 19:04:21.086 Injecting DmaFix...
09/01/2026 19:04:21.086 Injecting CustomOpcodeSystem...
09/01/2026 19:04:21.086 Injecting ScriptEngine: Phase 1
09/01/2026 19:04:21.086 Replaced call at: 0x0046A21B, original function was: 0x00469F00
09/01/2026 19:04:21.086 Replaced call at: 0x0058D552, original function was: 0x0058C080
09/01/2026 19:04:21.086 Replaced call at: 0x0058FCE4, original function was: 0x0058C080
09/01/2026 19:04:21.086 Replaced call at: 0x005D14D5, original function was: 0x005D4C40
09/01/2026 19:04:21.086 Replaced call at: 0x007487A8, original function was: 0x00745560
09/01/2026 19:04:21.086 Replaced call at: 0x0053BDD7, original function was: 0x00468D50
09/01/2026 19:04:21.086 Replaced call at: 0x005BA340, original function was: 0x00468D50
09/01/2026 19:04:21.086 Replaced call at: 0x005D4FD7, original function was: 0x00468D50
09/01/2026 19:04:21.086 Replaced call at: 0x00748E6B, original function was: 0x0053C900
09/01/2026 19:04:21.086 Replaced call at: 0x0053C758, original function was: 0x0053C550
09/01/2026 19:04:21.086 Replaced call at: 0x00748E04, original function was: 0x0053C550
09/01/2026 19:04:21.086 Replaced call at: 0x00748E3E, original function was: 0x0053C550
09/01/2026 19:04:21.086 
09/01/2026 19:04:21.086 Initializing CLEO core opcodes...
09/01/2026 19:04:21.086 Opcode [004E] registered
09/01/2026 19:04:21.086 Opcode [0050] registered
09/01/2026 19:04:21.086 Opcode [0051] registered
09/01/2026 19:04:21.086 Opcode [0417] registered
09/01/2026 19:04:21.086 Opcode [0A92] registered
09/01/2026 19:04:21.086 Opcode [0A93] registered
09/01/2026 19:04:21.086 Opcode [0A94] registered
09/01/2026 19:04:21.086 Opcode [0A95] registered
09/01/2026 19:04:21.086 Opcode [0AA0] registered
09/01/2026 19:04:21.086 Opcode [0AA1] registered
09/01/2026 19:04:21.086 Opcode [0AA9] registered
09/01/2026 19:04:21.086 Opcode [0AB1] registered
09/01/2026 19:04:21.086 Opcode [0AB2] registered
09/01/2026 19:04:21.086 Opcode [0AB3] registered
09/01/2026 19:04:21.086 Opcode [0AB4] registered
09/01/2026 19:04:21.086 Opcode [0DD5] registered
09/01/2026 19:04:21.086 Opcode [2000] registered
09/01/2026 19:04:21.086 Opcode [2002] registered
09/01/2026 19:04:21.086 Opcode [2003] registered
09/01/2026 19:04:21.086 
09/01/2026 19:04:21.086 Listing CLEO plugins:
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.Audio.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.DebugUtils.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.FileSystemOperations.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.GameEntities.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.IniFiles.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.Input.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.Math.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.MemoryOperations.cleo
09/01/2026 19:04:21.086  D:\GTA_SA\cleo\cleo_plugins\SA.Text.cleo
09/01/2026 19:04:21.086 
09/01/2026 19:04:21.086 Loading plugin 'cleo\cleo_plugins\SA.Text.cleo'
09/01/2026 19:04:21.086 Opcode [0390] registered
09/01/2026 19:04:21.086 Opcode [0391] registered
09/01/2026 19:04:21.086 Opcode [0ACA] registered
09/01/2026 19:04:21.086 Opcode [0ACB] registered
09/01/2026 19:04:21.086 Opcode [0ACC] registered
09/01/2026 19:04:21.086 Opcode [0ACD] registered
09/01/2026 19:04:21.086 Opcode [0ACE] registered
09/01/2026 19:04:21.086 Opcode [0ACF] registered
09/01/2026 19:04:21.086 Opcode [0AD0] registered
09/01/2026 19:04:21.086 Opcode [0AD1] registered
09/01/2026 19:04:21.086 Opcode [0AD3] registered
09/01/2026 19:04:21.086 Opcode [0AD4] registered
09/01/2026 19:04:21.086 Opcode [0ADB] registered
09/01/2026 19:04:21.086 Opcode [0ADE] registered
09/01/2026 19:04:21.086 Opcode [0ADF] registered
09/01/2026 19:04:21.086 Opcode [0AE0] registered
09/01/2026 19:04:21.086 Opcode [0AED] registered
09/01/2026 19:04:21.086 Opcode [2600] registered
09/01/2026 19:04:21.086 Opcode [2601] registered
09/01/2026 19:04:21.086 Opcode [2602] registered
09/01/2026 19:04:21.086 Opcode [2603] registered
09/01/2026 19:04:21.086 Opcode [2604] registered
09/01/2026 19:04:21.086 Opcode [2605] registered
09/01/2026 19:04:21.086 Opcode [2606] registered
09/01/2026 19:04:21.086 Opcode [2607] registered
09/01/2026 19:04:21.086 Opcode [2608] registered
09/01/2026 19:04:21.086 Opcode [2609] registered
09/01/2026 19:04:21.086 Error loading plugin 'cleo\cleo_plugins\SA.Text.cleo'
09/01/2026 19:04:21.086 
09/01/2026 19:04:21.086 Loading plugin 'cleo\cleo_plugins\SA.MemoryOperations.cleo'
09/01/2026 19:04:21.086 Opcode [0459] registered
09/01/2026 19:04:21.086 Opcode [0A8C] registered
09/01/2026 19:04:21.086 Opcode [0A8D] registered
09/01/2026 19:04:21.086 Opcode [0A96] registered
09/01/2026 19:04:21.086 Opcode [0A97] registered
09/01/2026 19:04:21.086 Opcode [0A98] registered
09/01/2026 19:04:21.086 Opcode [0A9F] registered
09/01/2026 19:04:21.086 Opcode [0AA2] registered
09/01/2026 19:04:21.086 Opcode [0AA3] registered
09/01/2026 19:04:21.086 Opcode [0AA4] registered
09/01/2026 19:04:21.086 Opcode [0AA5] registered
09/01/2026 19:04:21.086 Opcode [0AA6] registered
09/01/2026 19:04:21.086 Opcode [0AA7] registered
09/01/2026 19:04:21.086 Opcode [0AA8] registered
09/01/2026 19:04:21.086 Opcode [0AAA] registered
09/01/2026 19:04:21.086 Opcode [0ABA] registered
09/01/2026 19:04:21.086 Opcode [0AC6] registered
09/01/2026 19:04:21.086 Opcode [0AC7] registered
09/01/2026 19:04:21.086 Opcode [0AC8] registered
09/01/2026 19:04:21.086 Opcode [0AC9] registered
09/01/2026 19:04:21.086 Opcode [0AE9] registered
09/01/2026 19:04:21.086 Opcode [0AEA] registered
09/01/2026 19:04:21.086 Opcode [0AEB] registered
09/01/2026 19:04:21.086 Opcode [0AEC] registered
09/01/2026 19:04:21.086 Opcode [2400] registered
09/01/2026 19:04:21.086 Opcode [2401] registered
09/01/2026 19:04:21.086 Opcode [2402] registered
09/01/2026 19:04:21.086 Opcode [2403] registered
09/01/2026 19:04:21.086 Opcode [2404] registered
09/01/2026 19:04:21.086 Opcode [2405] registered
09/01/2026 19:04:21.086 Opcode [2406] registered
09/01/2026 19:04:21.086 Opcode [2407] registered
09/01/2026 19:04:21.086 Opcode [2408] registered
09/01/2026 19:04:21.086 
09/01/2026 19:04:21.086 Loading plugin 'cleo\cleo_plugins\SA.Math.cleo'
09/01/2026 19:04:21.096 Opcode [0A8E] registered
09/01/2026 19:04:21.096 Opcode [0A8F] registered
09/01/2026 19:04:21.096 Opcode [0A90] registered
09/01/2026 19:04:21.096 Opcode [0A91] registered
09/01/2026 19:04:21.096 Opcode [0AEE] registered
09/01/2026 19:04:21.096 Opcode [0AEF] registered
09/01/2026 19:04:21.096 Opcode [0B10] registered
09/01/2026 19:04:21.096 Opcode [0B11] registered
09/01/2026 19:04:21.096 Opcode [0B12] registered
09/01/2026 19:04:21.096 Opcode [0B13] registered
09/01/2026 19:04:21.096 Opcode [0B14] registered
09/01/2026 19:04:21.096 Opcode [0B15] registered
09/01/2026 19:04:21.096 Opcode [0B16] registered
09/01/2026 19:04:21.096 Opcode [0B17] registered
09/01/2026 19:04:21.096 Opcode [0B18] registered
09/01/2026 19:04:21.096 Opcode [0B19] registered
09/01/2026 19:04:21.096 Opcode [0B1A] registered
09/01/2026 19:04:21.096 Opcode [0B1B] registered
09/01/2026 19:04:21.096 Opcode [0B1C] registered
09/01/2026 19:04:21.096 Opcode [0B1D] registered
09/01/2026 19:04:21.096 Opcode [0B1E] registered
09/01/2026 19:04:21.096 Opcode [2700] registered
09/01/2026 19:04:21.096 Opcode [2701] registered
09/01/2026 19:04:21.096 Opcode [2702] registered
09/01/2026 19:04:21.096 Opcode [2703] registered
09/01/2026 19:04:21.096 Opcode [2704] registered
09/01/2026 19:04:21.096 Opcode [2705] registered
09/01/2026 19:04:21.096 Opcode [2706] registered
09/01/2026 19:04:21.096 Opcode [2707] registered
09/01/2026 19:04:21.096 Opcode [2708] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.Input.cleo'
09/01/2026 19:04:21.096 Opcode [0AB0] registered
09/01/2026 19:04:21.096 Opcode [0ADC] registered
09/01/2026 19:04:21.096 Opcode [2080] registered
09/01/2026 19:04:21.096 Opcode [2081] registered
09/01/2026 19:04:21.096 Opcode [2082] registered
09/01/2026 19:04:21.096 Opcode [2083] registered
09/01/2026 19:04:21.096 Opcode [2084] registered
09/01/2026 19:04:21.096 Opcode [2085] registered
09/01/2026 19:04:21.096 Opcode [2086] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.IniFiles.cleo'
09/01/2026 19:04:21.096 Opcode [0AF0] registered
09/01/2026 19:04:21.096 Opcode [0AF1] registered
09/01/2026 19:04:21.096 Opcode [0AF2] registered
09/01/2026 19:04:21.096 Opcode [0AF3] registered
09/01/2026 19:04:21.096 Opcode [0AF4] registered
09/01/2026 19:04:21.096 Opcode [0AF5] registered
09/01/2026 19:04:21.096 Opcode [2800] registered
09/01/2026 19:04:21.096 Opcode [2801] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.GameEntities.cleo'
09/01/2026 19:04:21.096 Opcode [0AB5] registered
09/01/2026 19:04:21.096 Opcode [0AB6] registered
09/01/2026 19:04:21.096 Opcode [0AB7] registered
09/01/2026 19:04:21.096 Opcode [0AB8] registered
09/01/2026 19:04:21.096 Opcode [0ABD] registered
09/01/2026 19:04:21.096 Opcode [0ABE] registered
09/01/2026 19:04:21.096 Opcode [0ABF] registered
09/01/2026 19:04:21.096 Opcode [0AD2] registered
09/01/2026 19:04:21.096 Opcode [0ADD] registered
09/01/2026 19:04:21.096 Opcode [0AE1] registered
09/01/2026 19:04:21.096 Opcode [0AE2] registered
09/01/2026 19:04:21.096 Opcode [0AE3] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.FileSystemOperations.cleo'
09/01/2026 19:04:21.096 Opcode [0A99] registered
09/01/2026 19:04:21.096 Opcode [0A9A] registered
09/01/2026 19:04:21.096 Opcode [0A9B] registered
09/01/2026 19:04:21.096 Opcode [0A9C] registered
09/01/2026 19:04:21.096 Opcode [0A9D] registered
09/01/2026 19:04:21.096 Opcode [0A9E] registered
09/01/2026 19:04:21.096 Opcode [0AAB] registered
09/01/2026 19:04:21.096 Opcode [0AE4] registered
09/01/2026 19:04:21.096 Opcode [0AE5] registered
09/01/2026 19:04:21.096 Opcode [0AE6] registered
09/01/2026 19:04:21.096 Opcode [0AE7] registered
09/01/2026 19:04:21.096 Opcode [0AE8] registered
09/01/2026 19:04:21.096 Opcode [0AD5] registered
09/01/2026 19:04:21.096 Opcode [0AD6] registered
09/01/2026 19:04:21.096 Opcode [0AD7] registered
09/01/2026 19:04:21.096 Opcode [0AD8] registered
09/01/2026 19:04:21.096 Opcode [0AD9] registered
09/01/2026 19:04:21.096 Opcode [0ADA] registered
09/01/2026 19:04:21.096 Opcode [0B00] registered
09/01/2026 19:04:21.096 Opcode [0B01] registered
09/01/2026 19:04:21.096 Opcode [0B02] registered
09/01/2026 19:04:21.096 Opcode [0B03] registered
09/01/2026 19:04:21.096 Opcode [0B04] registered
09/01/2026 19:04:21.096 Opcode [0B05] registered
09/01/2026 19:04:21.096 Opcode [2300] registered
09/01/2026 19:04:21.096 Opcode [2301] registered
09/01/2026 19:04:21.096 Opcode [2302] registered
09/01/2026 19:04:21.096 Opcode [2303] registered
09/01/2026 19:04:21.096 Opcode [2304] registered
09/01/2026 19:04:21.096 Opcode [2305] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.DebugUtils.cleo'
09/01/2026 19:04:21.096 Opcode [00C3] registered
09/01/2026 19:04:21.096 Opcode [00C4] registered
09/01/2026 19:04:21.096 Opcode [2100] registered
09/01/2026 19:04:21.096 Opcode [2101] registered
09/01/2026 19:04:21.096 Opcode [2102] registered
09/01/2026 19:04:21.096 
09/01/2026 19:04:21.096 Loading plugin 'cleo\cleo_plugins\SA.Audio.cleo'
09/01/2026 19:04:21.106 Opcode [0AAC] registered
09/01/2026 19:04:21.106 Opcode [0AAD] registered
09/01/2026 19:04:21.106 Opcode [0AAE] registered
09/01/2026 19:04:21.106 Opcode [0AAF] registered
09/01/2026 19:04:21.106 Opcode [0AB9] registered
09/01/2026 19:04:21.106 Opcode [0ABB] registered
09/01/2026 19:04:21.106 Opcode [0ABC] registered
09/01/2026 19:04:21.106 Opcode [0AC0] registered
09/01/2026 19:04:21.106 Opcode [0AC1] registered
09/01/2026 19:04:21.106 Opcode [0AC2] registered
09/01/2026 19:04:21.106 Opcode [0AC3] registered
09/01/2026 19:04:21.106 Opcode [0AC4] registered
09/01/2026 19:04:21.106 Opcode [0AC5] registered
09/01/2026 19:04:21.106 Opcode [2500] registered
09/01/2026 19:04:21.106 Opcode [2501] registered
09/01/2026 19:04:21.106 Opcode [2502] registered
09/01/2026 19:04:21.106 Opcode [2503] registered
09/01/2026 19:04:21.106 Opcode [2504] registered
09/01/2026 19:04:21.106 Opcode [2505] registered
09/01/2026 19:04:21.106 Opcode [2506] registered
09/01/2026 19:04:21.106 Opcode [2507] registered
09/01/2026 19:04:21.106 Opcode [2508] registered
09/01/2026 19:04:21.106 Opcode [2509] registered
09/01/2026 19:04:21.106 Opcode [250A] registered
09/01/2026 19:04:21.106 Opcode [250B] registered
09/01/2026 19:04:21.106 Opcode [250C] registered
09/01/2026 19:04:21.106 
09/01/2026 19:04:36.481 
09/01/2026 19:04:36.481 CLEO initialization: Phase 2
09/01/2026 19:04:36.481 Injecting ScriptEngine: Phase 2
09/01/2026 19:04:36.481 Injecting function at: 0x00463D50
09/01/2026 19:04:36.481 Replaced call at: 0x0053EBE4, original function was: 0x00532260
09/01/2026 19:04:36.481 Replaced call at: 0x0053E86C, original function was: 0x00532260
09/01/2026 19:04:36.481 Replaced call at: 0x0053E981, original function was: 0x0053BEE0
09/01/2026 19:04:36.481 
09/01/2026 19:04:36.481 Loaded plugins summary:
09/01/2026 19:04:36.481  GTA_SA.EXE (14383616 bytes)
09/01/2026 19:04:36.481  vorbisfile.dll (2352128 bytes)
09/01/2026 19:04:36.481  EAX.DLL (188416 bytes)
09/01/2026 19:04:36.481  vorbisHooked.dll (65536 bytes)
09/01/2026 19:04:36.481  ogg.dll (36864 bytes)
09/01/2026 19:04:36.481  vorbis.dll (1060864 bytes)
09/01/2026 19:04:36.481  CLEO.asi (475136 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.MemoryOperations.cleo (203264 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.Math.cleo (183296 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.Input.cleo (152064 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.IniFiles.cleo (173568 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.GameEntities.cleo (155136 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.FileSystemOperations.cleo (252928 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.DebugUtils.cleo (412672 bytes)
09/01/2026 19:04:36.481  cleo\cleo_plugins\SA.Audio.cleo (223744 bytes)
09/01/2026 19:04:36.481  bass.dll (143136 bytes)
09/01/2026 19:04:36.481 
```

After adding CrashInfo it reports problem during script processing:
```
GTA SA 1.0.0.0 US
Unhandled exception at 0x72D3F0A2 in SA.GameEntities.cleo (+0x1f0a2): 0xC0000005: Access violation writing location 0x00000071.
    Register dump:
        EAX: 0x72D3F0F7  EBX: 0x00000000  ECX: 0xBD6E8E6F  EDX: 0x00000000  
        EDI: 0x0000001B  ESI: 0x055781A0  EBP: 0x0028FD9C  EIP: 0x72D3F0A2  
        ESP: 0x0028FD8C  EFL: 0x00210246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0028FD8C:  72AAB3D5 00000000 0000000B BD418128 74C4BDEB 72AAA8D2
        0x0028FDA4:  0000000B 0053E871 0053ECD0 00619B71 0000001B 00000000
        0x0028FDBC:  00000001 0000000A 00748CC7 0000001B 00000000 706661F0
        0x0028FDD4:  00000000 0028FF88 7EFDE000 01C60000 00000001 03C60D08
        0x0028FDEC:  00000008 00000100 00000008 00000102 43A00000 43700000
        0x0028FE04:  00000000 00000000 00000280 000001E0 00000000 0028FE54
        0x0028FE1C:  001B35A2 00000200 00000000 00F40150 3920666C 00000150
        0x0028FE34:  000000F4 0000002C 00000000 00000001 FFFFFFFF FFFFFFFF
        0x0028FE4C:  FFFFFFFF FFFFFFFF 00000000 00000000 00000280 000001E0
        0x0028FE64:  008246F1 00400000 00000000 019455F3 0000000A 00000094
        base: 0x00090000   top: 0x0028FD8C   bottom: 0x00290000
        
    Backtrace (may be wrong):
        =>0x72D3F0A2 in SA.GameEntities.cleo (+0x1f0a2) (0x0028FD9C) 
          0x72AAA8D2 __enc$textbss$begin+0x198d2 in CLEO.asi (+0x1a8d2) (0x0028FDA4) 
          0x0053E871 _Z12FrontendIdlev+0x101 in GTA_SA.EXE (+0x13e871) (0x0028FDA8) 
          0x0053ECD0 AppEventHandler+0xc0 in GTA_SA.EXE (+0x13ecd0) (0x0053E871) 
          0x3C158B00 in unknown (+0x3c158b00) (0x0053E875) 
          0x5200C170 in unknown (+0x5200c170) (0x0053E879) 
          0x2AF8FEE8 in unknown (+0x2af8fee8) (0x0053E87D) 
          0x703CA100 XlatXdxInitXopServices+0x340ed0 in atiumdag.dll (+0x38a100) (0x0053E881) 
          0xE85000C1 in unknown (+0xe85000c1) (0x0053E885) 
          0x000DABB3 in unknown (+0xdabb3) (0x0053E889) 
          0xC308C483 in unknown (+0xc308c483) (0x0053E88D) 
          0x90909090 in unknown (+0x90909090) (0x0053E891) 
          0x90909090 in unknown (+0x90909090) (0x0053E895) 
          0x90909090 in unknown (+0x90909090) (0x0053E899) 
          0x8B909090 in unknown (+0x8b909090) (0x0053E89D) 
          0x8B042444 in unknown (+0x8b042444) (0x0053E8A1) 
          0x8B560850 in unknown (+0x8b560850) (0x0053E8A5) 
          0x72890470 in unknown (+0x72890470) (0x0053E8A9) 
          0x04508B04 in unknown (+0x4508b04) (0x0053E8AD) 
```

### PR DESCRIPTION
**Pull request by x87**
- fix #483 
- fix suspend macro messages
- fix stuck key presses after window unfocus
- fix hexadecimal numbers parsing in the config

### CODE REVIEW

File: cleo_plugins/Input/main.cpp [hunk 1]
```diff
@@ -54,8 +54,13 @@ class Input
...
+        // reset key states if game window is not active
+        if (GetForegroundWindow() != RsGlobal.ps->window)
+        {
+            keyStatesCurr->fill(0);
+            keyStatesPrev->fill(0);
+            return;
+        }
 
         std::swap(keyStatesCurr, keyStatesPrev);
         GetKeyboardState(keyStatesCurr->data());
```
Comment (MiranDMC) [inline cleo_plugins/Input/main.cpp]: Just do:
```
if (GetForegroundWindow() == RsGlobal.ps->window)
	GetKeyboardState(keyStatesCurr->data());
else
	keyStatesCurr->fill(0); // no inputs if window inactive
```

Comment (x87) [reply cleo_plugins/Input/main.cpp]: What about prev state?

Comment (MiranDMC) [reply cleo_plugins/Input/main.cpp]: Why prev state should be affected by current focus of the window?
Current zeroed state will become prev state on next frame.

All we do is ignoring new inputs if no focus. It might be more complicated with other key flags (like capslocks state), but we never use these so zero fill is fine.

Comment (x87) [reply cleo_plugins/Input/main.cpp]: I don't see prev state in your example

Comment (MiranDMC) [reply cleo_plugins/Input/main.cpp]: Yes. All we are updating is `GetKeyboardState(keyStatesCurr->data());` line. In the place where it is already.

Comment (x87) [reply cleo_plugins/Input/main.cpp]: I don't understand what's the difference then. Both prev and current state will be zeroed on unfocus

Comment (MiranDMC) [reply cleo_plugins/Input/main.cpp]: Prev state is always one frame behind. 
How difficult it is? No focus == no keys currently pressed. No more intervention in already existing logic is needed.
If we had command like "is_key_just_released" clearing both states would make it not working anymore.

Comment (x87) [reply cleo_plugins/Input/main.cpp]: Updated

Comment (MiranDMC) [reply cleo_plugins/Input/main.cpp]: Works.

**Comment by MiranDMC** [comment]
**CConfigManager::ReadInt** does not read hex numbers properly because it still tries to parse the `0x` part as an number.

File: cleo_plugins/Text/ScriptDrawsState.h [hunk 2]
```diff
@@ -2,8 +2,8 @@
 #include <CTheScripts.h>
 #include <CTxdStore.h>
 #include <CLEO_Utils.h>
-#include <CKeyGen.h>
 #include <array>
+#include "crc32.h"
```
Comment (MiranDMC) [inline cleo_plugins/Text/ScriptDrawsState.h]: ~~Should be included before array.~~
Well actually:
```
#include "crc32.h"
#include <CLEO_Utils.h>
#include <CTheScripts.h>
#include <CTxdStore.h>
#include <array>
```

As generally include orders should be:
* precompiled header
* this class header
* this project files
* local utils
* third party
* system includes
* language includes

**Comment by MiranDMC** [comment]
Now error messages do not mention the script will be suspended:
image

**Comment by x87** [comment]
> **CConfigManager::ReadInt** does not read hex numbers properly because it still tries to parse the `0x` part as an number.

[strtol](https://en.cppreference.com/w/c/string/byte/strtol) supports 0x prefix

image

File: cleo_plugins/DebugUtils/ScreenLog.h [hunk 3]
```diff
@@ -30,8 +30,8 @@ class ScreenLog
     CRGBA fontColor[4] = {
         // colors for eLogLevel
         CRGBA(0xDD, 0xDD, 0xDD, 0xFF), // None
-        CRGBA(0xFF, 0x30, 0xEE, 0xFF), // Error
         CRGBA(0xFF, 0xEE, 0x30, 0xFF), // User
+        CRGBA(0xFF, 0x30, 0xEE, 0xFF), // Error
```
Comment (x87) [inline cleo_plugins/DebugUtils/ScreenLog.h:34]: @MiranDMC Did it fix the message coloring issue?

Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScreenLog.h:34]: Hm changing values in ini has some effect but it is very chaotic. Still only what I was able to achieve is cyan, blue and opacity changes.
Is for sure the base valid?

Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScreenLog.h:34]: image

Comment (x87) [reply cleo_plugins/DebugUtils/ScreenLog.h:34]: Ok, thanks for catching that. I think it should work properly now (tested with hex values and integer)

**Review by MiranDMC — APPROVED** [review]
