### PR TITLE
Fix double script loading and execution

### LINKED ISSUE #486: Double script execution during game loading
When the game is loaded for the first time (cold start), all scripts are executed once before the actual game loop starts. 
This is an old issue, and exists in CLEO4 too. 

If the script does not have a wait instruction, its body will be processed causing side-effects and potentially crashing. It can be verified by writing an incrementing counter in the INI file: the value will be incremented by 2.

The same issue have been fixed in more recent versions of CLEO Redux.

### PR DESCRIPTION
**Pull request by x87**
Closes #486

### CODE REVIEW

File: source/CleoBase.cpp [hunk 1]
```diff
@@ -189,8 +200,7 @@ namespace CLEO
                 &GameRestartDebugDisplayTextBuffer_FrontendOrig
             );
             CodeInjector.ReplaceFunction(
-                OnUpdateGameLogics, VersionManager.TranslateMemoryAddress(MA_CALL_UPDATE_GAME_LOGICS),
-                &UpdateGameLogics_Orig
+                OnGameProcess, VersionManager.TranslateMemoryAddress(MA_CALL_GAME_PROCESS), &OnGameProcess_Orig
```
Comment (MiranDMC) [inline source/CleoBase.cpp:211]: This highlights how pointless auto format is. 
It should be splitting every param into new line, or do nothing at all. Currently it is basically glorified word wrap.
I'm looking at this diff and half of my screen is empty. Nobody is using 4:3 display monitors anymore.
