### PR TITLE
Argument count mismatch validation in 0AB2 split into critical and non critical cases.

### LINKED ISSUE #26: Mod Not Working
This mod is not working on CLEO 5, tested on alpha 25.

https://www.mixmods.com.br/2018/01/elm-emergency-lights-mod-v1-0-by-nyolc8/

### PR DESCRIPTION
**Pull request by MiranDMC**
Fixes #26

### CODE REVIEW

File: source/CCustomOpcodeSystem.cpp [hunk 1]
```diff
@@ -2304,11 +2304,15 @@ namespace CLEO
 				return CCustomOpcodeSystem::ErrorSuspendScript(thread);
 			}
 
-			if(returnParamCount - 1 != declaredParamCount) // minus 'num args' itself
```
Comment (x87) [inline source/CCustomOpcodeSystem.cpp:2307]: Should we disable this check only in CLEO4 compat mode (.cs4 extension)?

Comment (x87) [reply source/CCustomOpcodeSystem.cpp:2307]: I don't know, perhaps we should hsve a separate doc file which would list all differences for .cs4
