### PR TITLE
Script logging (cont.)

### LINKED ISSUE #433: Script Logs
## Requirements

- [ ] simple text-based format
- [ ] crash log
- [ ] visual indicator when log is active

## Nice to Have
- SBL formatted instructions
- Extra information on game state
- Ini-based configuration for log size budget, hotkey(s) to enable, log location

### PR DESCRIPTION
**Pull request by x87**
continuation of #369 

closes #433

### CODE REVIEW

**Comment by x87** [comment]
[cleo_script_log.txt](https://github.com/user-attachments/files/22630030/cleo_script_log.txt)

@MiranDMC what do you think?

**Comment by MiranDMC** [comment]
> [cleo_script_log.txt](https://github.com/user-attachments/files/22630030/cleo_script_log.txt)
> 
> @MiranDMC what do you think?

At first glance all these `|` looks weird but it is easy to get used to.
Currently the format is more flat, so there is no need for extra indentation of Frame block contents.
Generally looks fine.
Why `NEW GAME SESSION` is upper case, but `Frame` not?
After activating switching to the YAML syntax scripts are not recognized as foldable blocks.

**Comment by x87** [comment]
> Why NEW GAME SESSION is upper case, but Frame not?

Heading of different level (like H1 and H2)? Can be unified.


> After activating switching to the YAML syntax scripts are not recognized as foldable blocks.

Yeah I noticed it too, currently entire Frame content is flat. We can indent each script to let it fold if needed

**Comment by x87** [comment]
I also just noticed something

      |-- Script 35: cleo\launcher.cs (custom)
      |   {00000000} nop
      |   {00000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
      |   {00000024} terminate_this_script
      |-- Executed in 1 ms

      |-- Script 35: cleo\gasoline mod.cs (custom)


the script index is the same, need to check why

**Comment by x87** [comment]
```yaml
------------------------------------------------
  New Game Session
------------------------------------------------
  Time: 01/10/2025 14:42:10.718
  Main Script: original

------------------------------------------------
  Frame 6 (Active Scripts: 6)
------------------------------------------------

 -|-- Script 34: cleo\showsavescreen.cs (custom)
  |   {0000000} nop
  |   {0000002} wait {time} 250
 -|-- Executed in 0 ms

 -|-- Script 35: cleo\launcher.cs (custom)
  |   {0000000} nop
  |   {0000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission" 
  |   {0000024} terminate_this_script
 -|-- Executed in 1 ms

 -|-- Script 35: cleo\gasoline mod.cs (custom)
  |   {0000000} nop
  |   {0000002} script_name {name} "Gasoline Mod"
  |   {0000018} if
  |   {0000022}     is_game_first_start // BUG: non-logical command
  |   {0000024} goto_if_false @LABEL_123
  |   {0000031} 0@ = load_special_model {dff} "modelsqa\PetrolCan" {txd} "modelsqa\PetrolCan" // -> 0x109DFC68
  |   {0000076} write_int_to_ini_file {value} 0@(0x109DFC68) {path} "cleo\Gasoline Mod.ini" {section} "Models" {key} "PetrolCan"
  |   {0000123} 18@(0) = 255 // -> -1
  |   {0000130} 17@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Sound Volume" // -> 0.2
  |   {0000182} 20@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Sound Volume Gas Station" // -> 1.0
  |   {0000246} clear_local_var_bit_const {number} 21@(0) {bitIndex} 10
  |   {0000253} clear_local_var_bit_const {number} 21@(0) {bitIndex} 11
  |   {0000260} clear_local_var_bit_const {number} 21@(0) {bitIndex} 28
  |   {0000267} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Icon" // -> 1
  |   {0000318} if
  |   {0000322}     0@(1) == 1 // BUG: non-logical command
  |   {0000329} goto_if_false @LABEL_343
  |   {0000336} set_local_var_bit_const {number} 21@(0) {bitIndex} 28
  |   {0000343} clear_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 27
  |   {0000350} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Oil leaking mod" // -> 0
  |   {0000405} if
  |   {0000409}     0@(0) == 1 // BUG: non-logical command
  |   {0000416} goto_if_false @LABEL_430
  |   {0000430} clear_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 1
  |   {0000437} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Car" // -> 1
  |   {0000480} if
  |   {0000484}     0@(1) == 1 // BUG: non-logical command
  |   {0000491} goto_if_false @LABEL_505
  |   {0000498} set_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 1
  |   {0000505} clear_local_var_bit_const {number} 21@(0x10000002) {bitIndex} 2
  |   {0000512} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Big Car" // -> 1
  |   {0000559} if
  |   {0000563}     0@(1) == 1 // BUG: non-logical command
  |   {0000570} goto_if_false @LABEL_584
  |   {0000577} set_local_var_bit_const {number} 21@(0x10000002) {bitIndex} 2
  |   {0000584} clear_local_var_bit_const {number} 21@(0x10000006) {bitIndex} 3
  |   {0000591} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Quad" // -> 1
  |   {0000635} if
  |   {0000639}     0@(1) == 1 // BUG: non-logical command
  |   {0000646} goto_if_false @LABEL_660
  |   {0000653} set_local_var_bit_const {number} 21@(0x10000006) {bitIndex} 3
  |   {0000660} clear_local_var_bit_const {number} 21@(0x1000000E) {bitIndex} 4
  |   {0000667} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Helicopter" // -> 1
  |   {0000717} if
  |   {0000721}     0@(1) == 1 // BUG: non-logical command
  |   {0000728} goto_if_false @LABEL_742
  |   {0000735} set_local_var_bit_const {number} 21@(0x1000000E) {bitIndex} 4
  |   {0000742} clear_local_var_bit_const {number} 21@(0x1000001E) {bitIndex} 5
  |   {0000749} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Plane" // -> 1
  |   {0000794} if
  |   {0000798}     0@(1) == 1 // BUG: non-logical command
  |   {0000805} goto_if_false @LABEL_819
  |   {0000812} set_local_var_bit_const {number} 21@(0x1000001E) {bitIndex} 5
  |   {0000819} clear_local_var_bit_const {number} 21@(0x1000003E) {bitIndex} 6
  |   {0000826} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Boat" // -> 1
  |   {0000870} if
  |   {0000874}     0@(1) == 1 // BUG: non-logical command
  |   {0000881} goto_if_false @LABEL_895
  |   {0000888} set_local_var_bit_const {number} 21@(0x1000003E) {bitIndex} 6
  |   {0000895} clear_local_var_bit_const {number} 21@(0x1000007E) {bitIndex} 7
  |   {0000902} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Bike" // -> 1
  |   {0000946} if
  |   {0000950}     0@(1) == 1 // BUG: non-logical command
  |   {0000957} goto_if_false @LABEL_971
  |   {0000964} set_local_var_bit_const {number} 21@(0x1000007E) {bitIndex} 7
  |   {0000971} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 15
  |   {0000978} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Static Color" // -> 0
  |   {0001042} if
  |   {0001046}     0@(0) == 1 // BUG: non-logical command
  |   {0001053} goto_if_false @LABEL_1067
  |   {0001067} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 16
  |   {0001074} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 17
  |   {0001081} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 18
  |   {0001088} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 19
  |   {0001095} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 20
  |   {0001102} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 21
  |   {0001109} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Color" // -> 5
  |   {0001166} if
  |   {0001170}     0@(5) == 1 // BUG: non-logical command
  |   {0001177} goto_if_false @LABEL_1191
  |   {0001191} if
  |   {0001195}     0@(5) == 2 // BUG: non-logical command
  |   {0001202} goto_if_false @LABEL_1216
  |   {0001216} if
  |   {0001220}     0@(5) == 3 // BUG: non-logical command
  |   {0001227} goto_if_false @LABEL_1241
  |   {0001241} if
  |   {0001245}     0@(5) == 4 // BUG: non-logical command
  |   {0001252} goto_if_false @LABEL_1266
  |   {0001266} if
  |   {0001270}     0@(5) == 5 // BUG: non-logical command
  |   {0001277} goto_if_false @LABEL_1291
  |   {0001284} set_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 20
  |   {0001291} if
  |   {0001295}     0@(5) == 6 // BUG: non-logical command
  |   {0001302} goto_if_false @LABEL_1316
  |   {0001316} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 22
  |   {0001323} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 23
  |   {0001330} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 24
  |   {0001337} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Icon Position" // -> 1
  |   {0001397} if
  |   {0001401}     0@(1) == 1 // BUG: non-logical command
  |   {0001408} goto_if_false @LABEL_1422
  |   {0001415} set_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 22
  |   {0001422} if
  |   {0001426}     0@(1) == 2 // BUG: non-logical command
  |   {0001433} goto_if_false @LABEL_1447
  |   {0001447} if
  |   {0001451}     0@(1) == 3 // BUG: non-logical command
  |   {0001458} goto_if_false @LABEL_1472
  |   {0001472} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 29
  |   {0001479} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 12
  |   {0001486} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 13
  |   {0001493} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 14
  |   {0001500} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Gas Station Scene" {key} "Mode" // -> 1
  |   {0001553} if
  |   {0001557}     0@(1) == 0 // BUG: non-logical command
  |   {0001564} goto_if_false @LABEL_1578
  |   {0001578} if
  |   {0001582}     0@(1) == 1 // BUG: non-logical command
  |   {0001589} goto_if_false @LABEL_1603
  |   {0001596} set_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 12
  |   {0001603} if
  |   {0001607}     0@(1) == 2 // BUG: non-logical command
  |   {0001614} goto_if_false @LABEL_1628
  |   {0001628} if
  |   {0001632}     0@(1) == 3 // BUG: non-logical command
  |   {0001639} goto_if_false @LABEL_1653
  |   {0001653} clear_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 25
  |   {0001660} clear_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 26
  |   {0001667} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Mode" // -> 1
  |   {0001718} if
  |   {0001722}     0@(1) == 1 // BUG: non-logical command
  |   {0001729} goto_if_false @LABEL_1743
  |   {0001736} set_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 26
  |   {0001743} if
  |   {0001747}     0@(1) == 2 // BUG: non-logical command
  |   {0001754} goto_if_false @LABEL_1768
  |   {0001768} load_texture_dictionary {name} "GSMOD"
  |   {0001777} if
  |   {0001781}     is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 26 // BUG: non-logical command
  |   {0001788} goto_if_false @LABEL_1812
  |   {0001795} load_sprite {spriteSlot} 1 {textureName} "Line"
  |   {0001805} goto @LABEL_1823
  |   {0001823} load_sprite {spriteSlot} 2 {textureName} "point"
  |   {0001834} load_sprite {spriteSlot} 3 {textureName} "GSST"
  |   {0001844} load_sprite {spriteSlot} 4 {textureName} "full"
  |   {0001854} load_sprite {spriteSlot} 5 {textureName} "gsup"
  |   {0001864} if
  |   {0001868}     is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 26 // BUG: non-logical command
  |   {0001875} goto_if_false @LABEL_1900
  |   {0001882} load_sprite {spriteSlot} 6 {textureName} "Line2"
  |   {0001893} goto @LABEL_1912
  |   {0001912} load_sprite {spriteSlot} 7 {textureName} "mone"
  |   {0001922} load_sprite {spriteSlot} 8 {textureName} "batt"
  |   {0001932} load_sprite {spriteSlot} 9 {textureName} "GSST2"
  |   {0001943} 31@ = get_texture_from_sprite {spriteSlot} 1 // -> 0x214A4934
  |   {0001950} 30@ = get_texture_from_sprite {spriteSlot} 2 // -> 0x214A48D8
  |   {0001957} 29@ = get_texture_from_sprite {spriteSlot} 3 // -> 0x214A487C
  |   {0001964} 16@ = get_texture_from_sprite {spriteSlot} 4 // -> 0x214A4990
  |   {0001971} 14@ = get_texture_from_sprite {spriteSlot} 5 // -> 0x214A49EC
  |   {0001978} 13@ = get_texture_from_sprite {spriteSlot} 6 // -> 0x214A4A48
  |   {0001985} 11@ = get_texture_from_sprite {spriteSlot} 7 // -> 0x214A4AA4
  |   {0001992} 22@ = get_texture_from_sprite {spriteSlot} 8 // -> 0x214A4B00
  |   {0001999} 5@ = get_texture_from_sprite {spriteSlot} 9 // -> 0x214A4B5C
  |   {0002006} remove_texture_dictionary
  |   {0002008} 2@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon R" // -> 235
  |   {0002065} 3@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon G" // -> 20
  |   {0002122} 4@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon B" // -> 0
  |   {0002179} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon" // -> 1
  |   {0002234} if
  |   {0002238}     0@(1) == 1 // BUG: non-logical command
  |   {0002245} goto_if_false @LABEL_2964
  |   {0002252} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1944.852051 {y} -1769.553955 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0690
  |   {0002284} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2209.815918 {y} 2481.934082 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0708
  |   {0002316} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 604.880371 {y} 1705.272949 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0758
  |   {0002348} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -2414.48999 {y} 982.080994 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB05A0
  |   {0002380} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -2244.623047 {y} -2561.827881 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0820
  |   {0002412} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1327.511963 {y} 2678.106934 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0848
  |   {0002444} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -95.148804 {y} -1174.302979 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB08C0
  |   {0002476} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1679.982056 {y} 408.90509 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0CA8
  |   {0002508} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 652.030029 {y} -571.340027 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0CD0
  |   {0002540} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1605.896973 {y} -2714.251953 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0B18
  |   {0002572} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1471.47998 {y} 1864.310059 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0D70
  |   {0002604} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1596.5 {y} 2199.100098 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0E38
  |   {0002636} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2145.899902 {y} 2748.159912 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB14A0
  |   {0002668} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2642.110107 {y} 1106.530029 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145BC8
  |   {0002700} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2117.419922 {y} 920.419983 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145D30
  |   {0002732} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1381.680054 {y} 456.26001 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145D58
  |   {0002764} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1005.340271 {y} -936.017822 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145E20
  |   {0002796} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "SAxVCxLC Icons" // -> 0
  |   {0002850} if
  |   {0002854}     0@(0) == 1 // BUG: non-logical command
  |   {0002861} goto_if_false @LABEL_2964
  |   {0002964} gosub @LABEL_10054
  |   {0010054}     28@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Position X" // -> 52.0
  |   {0010116}     27@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Position Y" // -> 358.0
  |   {0010178}     26@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Size X" // -> 90.0
  |   {0010236}     25@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Size y" // -> 14.0
  |   {0010294}     24@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Alpha" // -> 200
  |   {0010351}     12@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Frame Alpha" // -> 150
  |   {0010414}     23@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Time" // -> 2000
  |   {0010458}     19@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Arrow Alpha" // -> 180
  |   {0010516}     15@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Size Icon" // -> 9.7
  |   {0010572}     return
  |   {0002971} wait {time} 0
 -|-- Executed in 8 ms

 -|-- Script 36: cleo\4567.cs (custom)
  |   {0000000} debug_on
  |   {0000002} 0@ = create_char {pedType} 4 {modelId} 489 {x} 0.0 {y} 0.0 {z} 0.0
```

**Comment by x87** [comment]
|   {0000563}     0@(1) == 1 // BUG: non-logical command

this doesn't look right, hmm

**Comment by x87** [comment]
@MiranDMC the condition result hook is not working correctly in debug build, you mentioned that you had that issue before, was it resolved?

**Comment by MiranDMC** [comment]
> @MiranDMC the condition result hook is not working correctly in debug build, you mentioned that you had that issue before, was it resolved?

The problem was random crashing, and it was not related to that hook. Fix to that is in master already.
Only in debug, that's weird.

**Comment by MiranDMC** [comment]
> I also just noticed something
> 
> ```
>   |-- Script 35: cleo\launcher.cs (custom)
>   |   {00000000} nop
>   |   {00000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
>   |   {00000024} terminate_this_script
>   |-- Executed in 1 ms
> 
>   |-- Script 35: cleo\gasoline mod.cs (custom)
> ```
> 
> the script index is the same, need to check why

The script is terminated, so it frees it's spot in the queue.

**Comment by x87** [comment]
> > I also just noticed something
> > ```
> >   |-- Script 35: cleo\launcher.cs (custom)
> >   |   {00000000} nop
> >   |   {00000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
> >   |   {00000024} terminate_this_script
> >   |-- Executed in 1 ms
> > 
> >   |-- Script 35: cleo\gasoline mod.cs (custom)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the script index is the same, need to check why
> 
> The script is terminated, so it frees it's spot in the queue.

hmm, right. a bit confusing, looks like a bug if you don't see it that way. would be nice to keep indexes persistent within the frame (or even within the session, so script 1 is always the same script)

**Comment by MiranDMC** [comment]
> ```yaml
> ------------------------------------------------
>   New Game Session
> ------------------------------------------------
>   Time: 01/10/2025 14:42:10.718
>   Main Script: original
> 
> ------------------------------------------------
>   Frame 6 (Active Scripts: 6)
> ------------------------------------------------
> 
>  -|-- Script 34: cleo\showsavescreen.cs (custom)
>   |   {0000000} nop
>   |   {0000002} wait {time} 250
>  -|-- Executed in 0 ms
> 
>  -|-- Script 35: cleo\launcher.cs (custom)
>   |   {0000000} nop
>   |   {0000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission" 
>   |   {0000024} terminate_this_script
>  -|-- Executed in 1 ms
> 
>  -|-- Script 35: cleo\gasoline mod.cs (custom)
>   |   {0000000} nop
>   |   {0000002} script_name {name} "Gasoline Mod"
>   |   {0000018} if
>   |   {0000022}     is_game_first_start // BUG: non-logical command
>   |   {0000024} goto_if_false @LABEL_123
>   |   {0000031} 0@ = load_special_model {dff} "modelsqa\PetrolCan" {txd} "modelsqa\PetrolCan" // -> 0x109DFC68
>   |   {0000076} write_int_to_ini_file {value} 0@(0x109DFC68) {path} "cleo\Gasoline Mod.ini" {section} "Models" {key} "PetrolCan"
>   |   {0000123} 18@(0) = 255 // -> -1
>   |   {0000130} 17@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Sound Volume" // -> 0.2
>   |   {0000182} 20@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Sound Volume Gas Station" // -> 1.0
>   |   {0000246} clear_local_var_bit_const {number} 21@(0) {bitIndex} 10
>   |   {0000253} clear_local_var_bit_const {number} 21@(0) {bitIndex} 11
>   |   {0000260} clear_local_var_bit_const {number} 21@(0) {bitIndex} 28
>   |   {0000267} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Icon" // -> 1
>   |   {0000318} if
>   |   {0000322}     0@(1) == 1 // BUG: non-logical command
>   |   {0000329} goto_if_false @LABEL_343
>   |   {0000336} set_local_var_bit_const {number} 21@(0) {bitIndex} 28
>   |   {0000343} clear_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 27
>   |   {0000350} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Oil leaking mod" // -> 0
>   |   {0000405} if
>   |   {0000409}     0@(0) == 1 // BUG: non-logical command
>   |   {0000416} goto_if_false @LABEL_430
>   |   {0000430} clear_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 1
>   |   {0000437} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Car" // -> 1
>   |   {0000480} if
>   |   {0000484}     0@(1) == 1 // BUG: non-logical command
>   |   {0000491} goto_if_false @LABEL_505
>   |   {0000498} set_local_var_bit_const {number} 21@(0x10000000) {bitIndex} 1
>   |   {0000505} clear_local_var_bit_const {number} 21@(0x10000002) {bitIndex} 2
>   |   {0000512} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Big Car" // -> 1
>   |   {0000559} if
>   |   {0000563}     0@(1) == 1 // BUG: non-logical command
>   |   {0000570} goto_if_false @LABEL_584
>   |   {0000577} set_local_var_bit_const {number} 21@(0x10000002) {bitIndex} 2
>   |   {0000584} clear_local_var_bit_const {number} 21@(0x10000006) {bitIndex} 3
>   |   {0000591} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Quad" // -> 1
>   |   {0000635} if
>   |   {0000639}     0@(1) == 1 // BUG: non-logical command
>   |   {0000646} goto_if_false @LABEL_660
>   |   {0000653} set_local_var_bit_const {number} 21@(0x10000006) {bitIndex} 3
>   |   {0000660} clear_local_var_bit_const {number} 21@(0x1000000E) {bitIndex} 4
>   |   {0000667} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Helicopter" // -> 1
>   |   {0000717} if
>   |   {0000721}     0@(1) == 1 // BUG: non-logical command
>   |   {0000728} goto_if_false @LABEL_742
>   |   {0000735} set_local_var_bit_const {number} 21@(0x1000000E) {bitIndex} 4
>   |   {0000742} clear_local_var_bit_const {number} 21@(0x1000001E) {bitIndex} 5
>   |   {0000749} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Plane" // -> 1
>   |   {0000794} if
>   |   {0000798}     0@(1) == 1 // BUG: non-logical command
>   |   {0000805} goto_if_false @LABEL_819
>   |   {0000812} set_local_var_bit_const {number} 21@(0x1000001E) {bitIndex} 5
>   |   {0000819} clear_local_var_bit_const {number} 21@(0x1000003E) {bitIndex} 6
>   |   {0000826} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Boat" // -> 1
>   |   {0000870} if
>   |   {0000874}     0@(1) == 1 // BUG: non-logical command
>   |   {0000881} goto_if_false @LABEL_895
>   |   {0000888} set_local_var_bit_const {number} 21@(0x1000003E) {bitIndex} 6
>   |   {0000895} clear_local_var_bit_const {number} 21@(0x1000007E) {bitIndex} 7
>   |   {0000902} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Bike" // -> 1
>   |   {0000946} if
>   |   {0000950}     0@(1) == 1 // BUG: non-logical command
>   |   {0000957} goto_if_false @LABEL_971
>   |   {0000964} set_local_var_bit_const {number} 21@(0x1000007E) {bitIndex} 7
>   |   {0000971} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 15
>   |   {0000978} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Static Color" // -> 0
>   |   {0001042} if
>   |   {0001046}     0@(0) == 1 // BUG: non-logical command
>   |   {0001053} goto_if_false @LABEL_1067
>   |   {0001067} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 16
>   |   {0001074} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 17
>   |   {0001081} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 18
>   |   {0001088} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 19
>   |   {0001095} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 20
>   |   {0001102} clear_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 21
>   |   {0001109} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Color" // -> 5
>   |   {0001166} if
>   |   {0001170}     0@(5) == 1 // BUG: non-logical command
>   |   {0001177} goto_if_false @LABEL_1191
>   |   {0001191} if
>   |   {0001195}     0@(5) == 2 // BUG: non-logical command
>   |   {0001202} goto_if_false @LABEL_1216
>   |   {0001216} if
>   |   {0001220}     0@(5) == 3 // BUG: non-logical command
>   |   {0001227} goto_if_false @LABEL_1241
>   |   {0001241} if
>   |   {0001245}     0@(5) == 4 // BUG: non-logical command
>   |   {0001252} goto_if_false @LABEL_1266
>   |   {0001266} if
>   |   {0001270}     0@(5) == 5 // BUG: non-logical command
>   |   {0001277} goto_if_false @LABEL_1291
>   |   {0001284} set_local_var_bit_const {number} 21@(0x100000FE) {bitIndex} 20
>   |   {0001291} if
>   |   {0001295}     0@(5) == 6 // BUG: non-logical command
>   |   {0001302} goto_if_false @LABEL_1316
>   |   {0001316} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 22
>   |   {0001323} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 23
>   |   {0001330} clear_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 24
>   |   {0001337} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Icon Position" // -> 1
>   |   {0001397} if
>   |   {0001401}     0@(1) == 1 // BUG: non-logical command
>   |   {0001408} goto_if_false @LABEL_1422
>   |   {0001415} set_local_var_bit_const {number} 21@(0x101000FE) {bitIndex} 22
>   |   {0001422} if
>   |   {0001426}     0@(1) == 2 // BUG: non-logical command
>   |   {0001433} goto_if_false @LABEL_1447
>   |   {0001447} if
>   |   {0001451}     0@(1) == 3 // BUG: non-logical command
>   |   {0001458} goto_if_false @LABEL_1472
>   |   {0001472} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 29
>   |   {0001479} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 12
>   |   {0001486} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 13
>   |   {0001493} clear_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 14
>   |   {0001500} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Gas Station Scene" {key} "Mode" // -> 1
>   |   {0001553} if
>   |   {0001557}     0@(1) == 0 // BUG: non-logical command
>   |   {0001564} goto_if_false @LABEL_1578
>   |   {0001578} if
>   |   {0001582}     0@(1) == 1 // BUG: non-logical command
>   |   {0001589} goto_if_false @LABEL_1603
>   |   {0001596} set_local_var_bit_const {number} 21@(0x105000FE) {bitIndex} 12
>   |   {0001603} if
>   |   {0001607}     0@(1) == 2 // BUG: non-logical command
>   |   {0001614} goto_if_false @LABEL_1628
>   |   {0001628} if
>   |   {0001632}     0@(1) == 3 // BUG: non-logical command
>   |   {0001639} goto_if_false @LABEL_1653
>   |   {0001653} clear_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 25
>   |   {0001660} clear_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 26
>   |   {0001667} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Mode" // -> 1
>   |   {0001718} if
>   |   {0001722}     0@(1) == 1 // BUG: non-logical command
>   |   {0001729} goto_if_false @LABEL_1743
>   |   {0001736} set_local_var_bit_const {number} 21@(0x105010FE) {bitIndex} 26
>   |   {0001743} if
>   |   {0001747}     0@(1) == 2 // BUG: non-logical command
>   |   {0001754} goto_if_false @LABEL_1768
>   |   {0001768} load_texture_dictionary {name} "GSMOD"
>   |   {0001777} if
>   |   {0001781}     is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 26 // BUG: non-logical command
>   |   {0001788} goto_if_false @LABEL_1812
>   |   {0001795} load_sprite {spriteSlot} 1 {textureName} "Line"
>   |   {0001805} goto @LABEL_1823
>   |   {0001823} load_sprite {spriteSlot} 2 {textureName} "point"
>   |   {0001834} load_sprite {spriteSlot} 3 {textureName} "GSST"
>   |   {0001844} load_sprite {spriteSlot} 4 {textureName} "full"
>   |   {0001854} load_sprite {spriteSlot} 5 {textureName} "gsup"
>   |   {0001864} if
>   |   {0001868}     is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 26 // BUG: non-logical command
>   |   {0001875} goto_if_false @LABEL_1900
>   |   {0001882} load_sprite {spriteSlot} 6 {textureName} "Line2"
>   |   {0001893} goto @LABEL_1912
>   |   {0001912} load_sprite {spriteSlot} 7 {textureName} "mone"
>   |   {0001922} load_sprite {spriteSlot} 8 {textureName} "batt"
>   |   {0001932} load_sprite {spriteSlot} 9 {textureName} "GSST2"
>   |   {0001943} 31@ = get_texture_from_sprite {spriteSlot} 1 // -> 0x214A4934
>   |   {0001950} 30@ = get_texture_from_sprite {spriteSlot} 2 // -> 0x214A48D8
>   |   {0001957} 29@ = get_texture_from_sprite {spriteSlot} 3 // -> 0x214A487C
>   |   {0001964} 16@ = get_texture_from_sprite {spriteSlot} 4 // -> 0x214A4990
>   |   {0001971} 14@ = get_texture_from_sprite {spriteSlot} 5 // -> 0x214A49EC
>   |   {0001978} 13@ = get_texture_from_sprite {spriteSlot} 6 // -> 0x214A4A48
>   |   {0001985} 11@ = get_texture_from_sprite {spriteSlot} 7 // -> 0x214A4AA4
>   |   {0001992} 22@ = get_texture_from_sprite {spriteSlot} 8 // -> 0x214A4B00
>   |   {0001999} 5@ = get_texture_from_sprite {spriteSlot} 9 // -> 0x214A4B5C
>   |   {0002006} remove_texture_dictionary
>   |   {0002008} 2@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon R" // -> 235
>   |   {0002065} 3@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon G" // -> 20
>   |   {0002122} 4@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon B" // -> 0
>   |   {0002179} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Map Icon" // -> 1
>   |   {0002234} if
>   |   {0002238}     0@(1) == 1 // BUG: non-logical command
>   |   {0002245} goto_if_false @LABEL_2964
>   |   {0002252} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1944.852051 {y} -1769.553955 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0690
>   |   {0002284} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2209.815918 {y} 2481.934082 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0708
>   |   {0002316} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 604.880371 {y} 1705.272949 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0758
>   |   {0002348} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -2414.48999 {y} 982.080994 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB05A0
>   |   {0002380} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -2244.623047 {y} -2561.827881 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0820
>   |   {0002412} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1327.511963 {y} 2678.106934 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0848
>   |   {0002444} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -95.148804 {y} -1174.302979 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB08C0
>   |   {0002476} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1679.982056 {y} 408.90509 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0CA8
>   |   {0002508} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 652.030029 {y} -571.340027 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0CD0
>   |   {0002540} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1605.896973 {y} -2714.251953 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0B18
>   |   {0002572} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} -1471.47998 {y} 1864.310059 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0D70
>   |   {0002604} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1596.5 {y} 2199.100098 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB0E38
>   |   {0002636} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2145.899902 {y} 2748.159912 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x5FB14A0
>   |   {0002668} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2642.110107 {y} 1106.530029 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145BC8
>   |   {0002700} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 2117.419922 {y} 920.419983 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145D30
>   |   {0002732} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1381.680054 {y} 456.26001 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145D58
>   |   {0002764} 1@ = add_cleo_blip {rwTextureOrRadarSprite} 5@(0x214A4B5C) {x} 1005.340271 {y} -936.017822 {short} true {red} 2@(235) {green} 3@(20) {blue} 4@(0) {alpha} 255 // -> 0x6145E20
>   |   {0002796} 0@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "SAxVCxLC Icons" // -> 0
>   |   {0002850} if
>   |   {0002854}     0@(0) == 1 // BUG: non-logical command
>   |   {0002861} goto_if_false @LABEL_2964
>   |   {0002964} gosub @LABEL_10054
>   |   {0010054}     28@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Position X" // -> 52.0
>   |   {0010116}     27@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Position Y" // -> 358.0
>   |   {0010178}     26@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Size X" // -> 90.0
>   |   {0010236}     25@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Size y" // -> 14.0
>   |   {0010294}     24@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Alpha" // -> 200
>   |   {0010351}     12@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Line Frame Alpha" // -> 150
>   |   {0010414}     23@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Settings" {key} "Time" // -> 2000
>   |   {0010458}     19@ = read_int_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Arrow Alpha" // -> 180
>   |   {0010516}     15@ = read_float_from_ini_file {path} "cleo\Gasoline Mod.ini" {section} "Visual Settings" {key} "Size Icon" // -> 9.7
>   |   {0010572}     return
>   |   {0002971} wait {time} 0
>  -|-- Executed in 8 ms
> 
>  -|-- Script 36: cleo\4567.cs (custom)
>   |   {0000000} debug_on
>   |   {0000002} 0@ = create_char {pedType} 4 {modelId} 489 {x} 0.0 {y} 0.0 {z} 0.0
> ```

Nice.
Number in Frame and Script could be prefixed with `#` to mark it is index.

**Comment by x87** [comment]
>Number in Frame and Script could be prefixed with # to mark it is index.

I had it, but # is a comment in YAML so it looks a bit weird when highlighted in n++

**Comment by MiranDMC** [comment]
> > > I also just noticed something
> > > ```
> > >   |-- Script 35: cleo\launcher.cs (custom)
> > >   |   {00000000} nop
> > >   |   {00000002} load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
> > >   |   {00000024} terminate_this_script
> > >   |-- Executed in 1 ms
> > > 
> > >   |-- Script 35: cleo\gasoline mod.cs (custom)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the script index is the same, need to check why
> > 
> > 
> > The script is terminated, so it frees it's spot in the queue.
> 
> hmm, right. a bit confusing, looks like a bug if you don't see it that way. would be nice to keep indexes persistent within the frame (or even within the session, so script 1 is always the same script)

Seems a lot of work for it. You can also print the pointer of the script struct. That is unique identifier of the script.
Question is does anybody actually need it?
By looking at script number it is easy to tell no scripts were executed meanwhile (printing of some scripts can be disabled in config), or if it is fake script injected from plugins.

**Comment by MiranDMC** [comment]
> > Number in Frame and Script could be prefixed with # to mark it is index.
> 
> I had it, but # is a comment in YAML so it looks a bit weird when highlighted in n++

Well, N++ has option to define custom user language.

**Comment by x87** [comment]
> @MiranDMC the condition result hook is not working correctly in debug build, you mentioned that you had that issue before, was it resolved?

oh boy, it's even more complicated. I have imfast plugin and it skips main menu and automatically load last save. I have this script

```
{$CLEO .cs}
debug_on
{009A:} 0@ = create_char {pedType} 4 {modelId} #RANCHER {x} 0 {y} 0 {z} 0
```

because there is no wait command, it crashes right after loading is complete. Now, guess what happens? The hook is not installed yet, as OnDrawingFinished was never called.

**Comment by MiranDMC** [comment]
> > @MiranDMC the condition result hook is not working correctly in debug build, you mentioned that you had that issue before, was it resolved?
> 
> oh boy, it's even more complicated. I have imfast plugin and it skips main menu and automatically load last save. I have this script
> 
> ```
> {$CLEO .cs}
> debug_on
> {009A:} 0@ = create_char {pedType} 4 {modelId} #RANCHER {x} 0 {y} 0 {z} 0
> ```
> 
> because there is no wait command, it crashes right after loading is complete. Now, guess what happens? The hook is not installed yet, as OnDrawingFinished was never called.

Hm, there was problems with the imfast before and I thought these are fixed already. I think OnGameStart had extra call to late initialization just for that case.

**Comment by x87** [comment]
> > > @MiranDMC the condition result hook is not working correctly in debug build, you mentioned that you had that issue before, was it resolved?
> > 
> > 
> > oh boy, it's even more complicated. I have imfast plugin and it skips main menu and automatically load last save. I have this script
> > ```
> > {$CLEO .cs}
> > debug_on
> > {009A:} 0@ = create_char {pedType} 4 {modelId} #RANCHER {x} 0 {y} 0 {z} 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because there is no wait command, it crashes right after loading is complete. Now, guess what happens? The hook is not installed yet, as OnDrawingFinished was never called.
> 
> Hm, there was problems with the imfast before and I thought these are fixed already. I think OnGameStart had extra call to late initialization just for that case.

in core, but not plugins

**Comment by x87** [comment]
yeah, if I move hook install from ondrawing to OnScriptOpcodeProcessBefore it works fine

  |   {0000318} if
  |   {0000322}     0@(1) == 1 // -> condition: true
  |   {0000329} goto_if_false @LABEL_343

**Comment by x87** [comment]
@MiranDMC any specific reason hook install was put to OnDrawingFinished? avoiding hook conflicts?

**Comment by MiranDMC** [comment]
> yeah, if I move hook install from ondrawing to OnScriptOpcodeProcessBefore it works fine
> 
> | {0000318} if | {0000322} 0@(1) == 1 // -> condition: true | {0000329} goto_if_false @LABEL_343

You still wanted to add check for already existing hooks here.

**Comment by MiranDMC** [comment]
Quick Notepad++ user syntax:
[CLEO_Log.xml](https://github.com/user-attachments/files/22651511/CLEO_Log.xml)
It works well if script closing sequence is prefixed with ` |--`
No idea yet how to make it work with session/frame blocks

**Comment by x87** [comment]
> It works well if script closing sequence is prefixed with  |--

it ends with -|-- now, but can be changed to |--. I think it will look even prettier.

**Comment by x87** [comment]
> Quick Notepad++ user syntax: [CLEO_Log.xml](https://github.com/user-attachments/files/22651511/CLEO_Log.xml) It works well if script closing sequence is prefixed with ` |--` No idea yet how to make it work with session/frame blocks

take a look how YAML collapses blocks based on indentation

**Comment by MiranDMC** [comment]
Why offsets padding style was changed? This is not how Sanny decompiles scripts. Now searching for `{0000480}` will lead to no results.

**Comment by x87** [comment]
> Why offsets padding style was changed? This is not how Sanny decompiles scripts. Now searching for `{0000480}` will lead to no results.

can you show side by side what offsets look like in log and sb?

**Comment by x87** [comment]
> > yeah, if I move hook install from ondrawing to OnScriptOpcodeProcessBefore it works fine
> > | {0000318} if | {0000322} 0@(1) == 1 // -> condition: true | {0000329} goto_if_false @LABEL_343
> 
> You still wanted to add check for already existing hooks here.

updated to call the original function

> Why offsets padding style was changed? This is not how Sanny decompiles scripts. Now searching for `{0000480}` will lead to no results.

reverted offsets to your variant

```
 -|-- Script 35: cleo\launcher.cs (custom)
  |         {0}   nop
  |         {2}   load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
  |        {24}   terminate_this_script
  |-- Executed in 0 ms
```

**Comment by MiranDMC** [comment]
> > > yeah, if I move hook install from ondrawing to OnScriptOpcodeProcessBefore it works fine
> > > | {0000318} if | {0000322} 0@(1) == 1 // -> condition: true | {0000329} goto_if_false @LABEL_343
> > 
> > 
> > You still wanted to add check for already existing hooks here.
> 
> updated to call the original function
> 
> > Why offsets padding style was changed? This is not how Sanny decompiles scripts. Now searching for `{0000480}` will lead to no results.
> 
> reverted offsets to your variant
> 
> ```
>  -|-- Script 35: cleo\launcher.cs (custom)
>   |         {0}   nop
>   |         {2}   load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
>   |        {24}   terminate_this_script
>   |-- Executed in 0 ms
> ```

Uh, you just killed game performance. Check original fullscreen without frame limiter.
I mean you had idea to check if there was hook installed in first place, then somehow call it.

**Comment by x87** [comment]
> > > > yeah, if I move hook install from ondrawing to OnScriptOpcodeProcessBefore it works fine
> > > > | {0000318} if | {0000322} 0@(1) == 1 // -> condition: true | {0000329} goto_if_false @LABEL_343
> > > 
> > > 
> > > You still wanted to add check for already existing hooks here.
> > 
> > 
> > updated to call the original function
> > > Why offsets padding style was changed? This is not how Sanny decompiles scripts. Now searching for `{0000480}` will lead to no results.
> > 
> > 
> > reverted offsets to your variant
> > ```
> >  -|-- Script 35: cleo\launcher.cs (custom)
> >   |         {0}   nop
> >   |         {2}   load_and_launch_custom_mission {scriptFileName} "add_money_mission"  // -> condition: false
> >   |        {24}   terminate_this_script
> >   |-- Executed in 0 ms
> > ```
> 
> Uh, you just killed game performance. Check original fullscreen without frame limiter. I mean you had idea to check if there was hook installed in first place, then somehow call it.

Killed how? How does it make slower than anything else we added for each opcode and each argument?

**Comment by x87** [comment]
We can see if people report slowness, but adding an extra call is a drop in ocean comparing to amount of LogAppend calls

**Comment by x87** [comment]
@MiranDMC changed log setup - now disabling it in the config won't affect the game state. in case it causes some performance issues, or something, people can just disable it.

also removed CLOG cheat because it has less sense with this new behavior, everything is config based. Also no need to worry about log indicator and such, and possible conflicts with CLOG being used in some scripts.

**Comment by MiranDMC** [comment]
> @MiranDMC changed log setup - now disabling it in the config won't affect the game state. in case it causes some performance issues, or something, people can just disable it.
> 
> also removed CLOG cheat because it has less sense with this new behavior, everything is config based. Also no need to worry about log indicator and such, and possible conflicts with CLOG being used in some scripts.

So you are doing performance related changes without conducting even single test...

Config what? Currently all you need to do is type the cheat. I can't wait to explain all the noobs to modify some config in order to get log.
What new behavior? Due to performance costs log can not be enabled by default. It also would destroy automatic log from last frame on crash.

**Comment by x87** [comment]
Crash log is enabled by default. It covers most of the needs.
Those who are willing to profile their scripts would know how to change a line in the ini file.

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 1]
```diff
@@ -0,0 +1,1112 @@
...
+            {
+                if (hasFlags) LogAppend(", ");
+                LogAppend("debug");
+                hasFlags = true;
+            }
+            LogAppend(")");
+        }
+
+        auto ver = CLEO_GetScriptVersion(script);
+        if (ver != eCLEO_Version::CLEO_VER_CUR)
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp:247]: This should be reported along with other flags. Why introducing new contention (square brackets).
It also make no sense to use short form. Let's make everyone understand what it actually means:
`(debug, CLEO4 compatibility mode)`

Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:247]: Can you provide an example of how it is logged now, and how you want it to change?

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 2]
```diff
@@ -0,0 +1,1112 @@
...
+            {
+                packName = pack.name;
+                break;
+            }
+        }
+
+        LogAppend("------------------------------------------------\n");
+        LogAppend("  New Game Session\n");
+        LogAppend("------------------------------------------------\n");
+        LogAppend("  Time: ");
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp]: These thing are logged after the block header, meanwhile Frame header properties are logged inside, in single line.
Both should use same format.
Maybe print the properties inside header, but as list in new lines?

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 3]
```diff
@@ -0,0 +1,1112 @@
...
+        for (const auto& pack : FrontEndMenuManager.m_MissionPacks)
+        {
+            if (pack.id == FrontEndMenuManager.m_nSelectedMissionPack)
+            {
+                packName = pack.name;
+                break;
+            }
+        }
+
+        LogAppend("------------------------------------------------\n");
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp]: Block decorator should be defined as constant, next to **Block_Indent** variable.
Having two different markers for block opening and closing would give chance to write block detection in Notepad++.
Opening line could be for example `+------------------------------------------------`

File: cleo_plugins/DebugUtils/ScriptLog.cpp (hunk 2 above)
Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp]: yes, because the session is printed once, and the frame is printed each , um, frame. Saving lines.

`New Game Session (Time: {}, Mission Pack: {}, Mission Pack Name: {})` probably would not fit into a single line.

Moving ----- separator down is okay.

**Comment by MiranDMC** [comment]
> Crash log is enabled by default. It covers most of the needs. Those who are willing to profile their scripts would know how to change a line in the ini file.

It kills case where there is script problem. Even recently I was debugging my script that way.
Do actions ingame to setup the problematic scenario, type the cheat then do the action.
It saves a lot of time and reading megabytes of unneeded log.
Thinking I would need to close the game, go to config file and edit it, then start game again... I will probably stay with SCRLog

You also killed feature of reloading config when game session is started. So it is totally inconvenient now.

File: cleo_plugins/DebugUtils/ScriptLog.cpp (hunk 2 above)
Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScriptLog.cpp]: Ok, then at least put these data into the block.
Maybe the entire block, including the data should starts with comments `//`? It would be colored in editors and in Sanny.

File: cleo_plugins/DebugUtils/ScriptLog.cpp (hunk 1 above)
Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:247]: Is
` -|-- Script 3: .\.cleo_tests_runner.cs4 (custom) [compat: CLEO4]`
could be
` -|-- Script 3: .\.cleo_tests_runner.cs4 (custom, CLEO4 compatibility mode)` 

I wonder if parenthesis is good choice. Closing one introduces nothing.
Could be:
` -|-- Script 3: .\.cleo_tests_runner.cs4 - custom, CLEO4 compatibility mode` 

Same with frame info:
```
------------------------------------------------
  Frame 62 - Active Scripts: 3
------------------------------------------------
```

**Comment by x87** [comment]
> > Crash log is enabled by default. It covers most of the needs. Those who are willing to profile their scripts would know how to change a line in the ini file.
> 
> It kills case where there is script problem. Even recently I was debugging my script that way. Do actions ingame to setup the problematic scenario, type the cheat then do the action. It saves a lot of time and reading megabytes of unneeded log. Thinking I would need to close the game, go to config file and edit it, then start game again... I will probably stay with SCRLog
> 
> You also killed feature of reloading config when game session is started. So it is totally inconvenient now.

I have no idea what are you talking about. Log/Hooks/Reload is enabled by default. Nothing is removed except for CLOG cheat. If you need to troubleshoot a script, enable full log, reproduce the problem and go read the log file.

Previous implementation was lacking a way to disable all intrusive hooks when I don't need them. Now it's there

File: cleo_plugins/DebugUtils/ScriptLog.cpp (hunk 3 above)
Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp]: It works fine with YAML language in N++. Everything is collapsible.

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 4]
```diff
@@ -0,0 +1,1116 @@
...
+        LogAppend(" -|-- Script ");
+        LogAppendNum(scriptIdx);
+        LogAppend(": ");
+        LogAppend(filename);
+
+        // Add flags in parentheses
+        bool hasFlags = false;
+        if (script->IsCustom() || script->IsMission() || CLEO_GetScriptDebugMode(script))
+        {
+            LogAppend(" -");
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp]: Missing whitespace after the `-`?

**Comment by MiranDMC** [comment]
> > > Crash log is enabled by default. It covers most of the needs. Those who are willing to profile their scripts would know how to change a line in the ini file.
> > 
> > 
> > It kills case where there is script problem. Even recently I was debugging my script that way. Do actions ingame to setup the problematic scenario, type the cheat then do the action. It saves a lot of time and reading megabytes of unneeded log. Thinking I would need to close the game, go to config file and edit it, then start game again... I will probably stay with SCRLog
> > You also killed feature of reloading config when game session is started. So it is totally inconvenient now.
> 
> I have no idea what are you talking about. Log/Hooks/Reload is enabled by default. Nothing is removed except for CLOG cheat. If you need to troubleshoot a script, enable full log, reproduce the problem and go read the log file.
> 
> Previous implementation was lacking a way to disable all intrusive hooks when I don't need them. Now it's there

Config file was reloaded whenever CLOG was used.
Intrusive hooks? CLEO_UnregisterCallback can be used when disabling the log, but I did not found it necessary after spending time analyzing execution with profiler.

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 5]
```diff
@@ -0,0 +1,1116 @@
...
+            bool savingEnabled = !script->IsCustom() || false; // TODO: check CLEO save enabled for custom script
+            if (savingEnabled && cleoStack)
+            {
+                LogAppend(" \\ BUG: Script saving enabled. Saving during cleo_call would result in errors!");
+            }
+
+            bool wastedBustedCheck = script->IsMission() && script->bWastedBustedCheck;
+            if (wastedBustedCheck && cleoStack)
+            {
+                LogAppend(
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp:286]: Another great example of "improved formatting"

**Review by MiranDMC — APPROVED** [review]
Every decision in my code was based on extensive testing. If you changing something without bench-marking you most likely making it worse.

Eh, I have better things to do than assisting in butchering my hard work.
Do whatever you want.

**Comment by x87** [comment]
> > > > Crash log is enabled by default. It covers most of the needs. Those who are willing to profile their scripts would know how to change a line in the ini file.
> > > 
> > > 
> > > It kills case where there is script problem. Even recently I was debugging my script that way. Do actions ingame to setup the problematic scenario, type the cheat then do the action. It saves a lot of time and reading megabytes of unneeded log. Thinking I would need to close the game, go to config file and edit it, then start game again... I will probably stay with SCRLog
> > > You also killed feature of reloading config when game session is started. So it is totally inconvenient now.
> > 
> > 
> > I have no idea what are you talking about. Log/Hooks/Reload is enabled by default. Nothing is removed except for CLOG cheat. If you need to troubleshoot a script, enable full log, reproduce the problem and go read the log file.
> > Previous implementation was lacking a way to disable all intrusive hooks when I don't need them. Now it's there
> 
> Config file was reloaded whenever CLOG was used. Intrusive hooks? CLEO_UnregisterCallback can be used when disabling the log, but I did not found it necessary after spending time analyzing execution with profiler.

I have no idea how CLOG is even remotely useful. When you enable full logging, the size limit only lets you to save last 2-3 seconds of gameplay. So to get your data in the log you need type CLOG in very narrow time window. Not to mention that the file will log ALL active scripts. Good luck tracing it.

If you really want to debug something specific, use Enabled = 2 and OnlyDebugScripts = 1 and add `debug_on` around code you are interested. THEN you get logs without unnecessary noise.

**Comment by MiranDMC** [comment]
Error messages from eCallbackId::Log could be printed in the log too, as currently this is how script with dead loop is logged:
```
  |         {4}   trace {text} "test" 
  |        {13}   goto @LABEL_4
  |         {4}   trace {text} "test" 
  |        {13}   goto @LABEL_4

  |-- Executed in 12582 ms
```

**Comment by x87** [comment]
updated block style

[_cleo_script_log.txt](https://github.com/user-attachments/files/22688844/_cleo_script_log.txt)


```yaml

--|-- Frame 7 - Active Scripts: 36
  |
 -|-- Script 25: cleo\showsavescreen.cs - custom
  |   Sleeping for 217 ms more
  |-- Executed in 0 ms
  |
 -|-- Script 26: cleo\gasoline mod.cs - custom
  |      {2975}   if
  |      {2979}       is_player_playing {self} 0 // -> condition: true
  |      {2983}   goto_if_false @LABEL_8646
  |      {2990}   if and
  |      {2994}       $43(0) == 0 // -> condition: true
  |      {3001}       is_char_in_any_car {self} $3(1) // -> condition: false
  |      {3006}   goto_if_false @LABEL_8433
  |      {8433}   clear_local_var_bit_const {number} 21@(0x145010FE) {bitIndex} 11
  |      {8440}   clear_local_var_bit_const {number} 21@(0x145010FE) {bitIndex} 10
  |      {8447}   gosub @LABEL_9697
  |      {9697}       if and
  |      {9701}           not is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 10 // -> condition: true
  |      {9708}           not 18@(-1) == 255 // -> condition: false
  |      {9715}       goto_if_false @LABEL_9741
  |      {9741}       return
  |      {8454}   gosub @LABEL_9865
  |      {9865}       if and
  |      {9869}           not is_local_var_bit_set_const {number} 21@(0x145010FE) {bitIndex} 11 // -> condition: true
  |      {9876}           not 18@(-1) == 255 // -> condition: false
  |      {9883}       goto_if_false @LABEL_9909
  |      {9909}       return
  |      {8461}   if and
  |      {8465}       not is_char_in_any_car {self} $3(1) // -> condition: true
  |      {8470}       $43(0) == 0 // -> condition: true
  |      {8477}       $409(0) == 0 // -> condition: true
  |      {8484}   goto_if_false @LABEL_8646
  |      {8491}   9@(0) = 0 // -> 0
  |      {8498}   {progress} 9@ {anyCar} 0@ = get_any_car_no_save_recursive {progress} 9@(0) // -> 0, -1, condition: false
  |      {8509}   goto_if_false @LABEL_8646
  |      {8646}   goto @LABEL_2971
  |      {2971}   wait {time} 0
  |-- Executed in 0 ms
  |
 -|-- Script 27: cleo\4567.cs - custom
  |         {4}   shake_cam {intensity} 1
  |         {8}   shake_cam {intensity} 2
  |        {12}   shake_cam {intensity} 3
  |        {16}   debug_on
  |        {18}   shake_cam {intensity} 4
  |        {22}   shake_cam {intensity} 5
  |        {26}   0@ = create_char {pedType} 4 {modelId} 489 {x} 0.0 {y} 0.0 {z} 0.0
```

**Comment by x87** [comment]
image

**Comment by x87** [comment]
Renamed .cleo_script_log.txt to _cleo_script_log.txt as GitHub does not allow attaching the former

**Comment by x87** [comment]
Also, current session header should always be added to the log, irrespective of settings.

**Comment by x87** [comment]
@MiranDMC I kinda want to move log file to the root. CLEO folder is very crowded and its difficult to find the file sometimes. Also cleo.log and _cleo_script_log.txt would better be next to each other. What do you think?

I know root is also crowded, but I can't think of a better place.

**Comment by MiranDMC** [comment]
> @MiranDMC I kinda want to move log file to the root. CLEO folder is very crowded and its difficult to find the file sometimes. Also cleo.log and _cleo_script_log.txt would better be next to each other. What do you think?
> 
> I know root is also crowded, but I can't think of a better place.

Makes sense. Then it should be named without the prefix, so it is actually next to the CLEO.asi.
`cleo.log` should probably be renamed to `CLEO.log`. How about dedicated filetype for the log itself, like `CLEO_script_log.clog`? Then notepad would be able to automatically select proper syntax highlight.

At other hand, some people were already very unhappy the cleo.log is back there. 
Also, log will be in root, but config file needed to enable it deep in `cleo\plugins`.

Hm it actually makes it reasonable to think again about moving the cleo.log to cleo dir, and delete one in the root if it exists.
Most if not all of other ASI plugins can be installed in ModLoader, so people actually are keeping the root tidy.
Prefixing with dot was nice. Take note the `.cleo_config.ini` is also there.

**Comment by x87** [comment]
> Prefixing with dot was nice.

Yes, but you can't attach it to GitHub. People will have constant issues.

Ideally, I would have one log and one config file. Why can't plugins read from .cleo_config.ini?
Why not add script log directly to cleo.log? It has many extra information. I guess it would also solve the eCallbackId::Log thingy you mentioned.

there is also some duplicated meta info between two logs:
```
03/10/2025 18:46:40.790 Starting new game session, save slot: -1
03/10/2025 18:46:40.923 Loading custom script 'c:\work\gta_games\grand theft auto san andreas\cleo\4567.cs'...
03/10/2025 18:46:40.923 Registering custom script named '4567.cs'
```

```
------------------------------------------------
  New Game Session
------------------------------------------------
  Time: 01/10/2025 14:42:10.718
  Main Script: original


 -|-- Script 36: cleo\4567.cs (custom)
```

cleo.log already provides info about current session, we can just add frame trace from script log here and it will present full flow from start to finish, in a single file. the only challenge I see, is around flushing when the file exceeds the limit.

**Comment by x87** [comment]
[cleo.log](https://github.com/user-attachments/files/22699935/cleo.log)

it could look like this with a crash log added to cleo.log

**Comment by x87** [comment]
[cleo.log](https://github.com/user-attachments/files/22699949/cleo.log)

or without timestamps

**Comment by MiranDMC** [comment]
> [cleo.log](https://github.com/user-attachments/files/22699949/cleo.log)
> 
> or without timestamps

Ok, but is there last frame log always available? I think it might not in case of full log mode.
You can log "Script execution log:\n" + script log. Then only first line will have the timestamp.

Still, if log error messages were logged in script log it would be immediately apparent which command produced pink warning messages on screen.

**Comment by x87** [comment]
> Ok, but is there last frame log always available? I think it might not in case of full log mode.

in full log mode you would have all frames logged from the start of the first session to the end of the game.

```
03/10/2025 18:46:40.923 stardard cleo.log starts
03/10/2025 18:46:40.923 ...
03/10/2025 18:46:40.923 ...
|-frame 0
|-frame 1
| ....
|-frame 12415
03/10/2025 18:46:40.923 ... game restarts
03/10/2025 18:46:40.923 ... stardard cleo.log info
|-frame 0
|-frame 1
| ....
|-frame 345
03/10/2025 18:46:40.923 ...
03/10/2025 18:46:40.923 standard cleo.log ends
```

the problem here is that the file will be huge if you don't limit the log to the debug scripts only. Truncating it is problematic if you want to preserve "standard log" messages. I guess that's the only downside of this method.

I'm personally fine with not limiting the log file size at all, as I think the default crash log or debug only scripts produce a compact enough file.
If someone wants to trace ALL scripts, well, good luck dealing with 5GB file :D

**Comment by x87** [comment]
FOR FULL LOG case (or always?)

Potentially, we can still log to _script_log.txt but at the end when we close the game and flush cleo.log, merge content of _script_log.txt with cleo.log.

so, in cleo.log you would have

```
03/10/2025 18:46:40.923 stardard cleo.log starts
03/10/2025 18:46:40.923 ...
03/10/2025 18:46:40.923 ... new game session
## SCRIPT_LOG_GOES_HERE ##
```

then we open _script_log.txt and log/truncate content here, then when the session ends for whatever reason, we take its content and replace ## SCRIPT_LOG_GOES_HERE ## with it.

```
03/10/2025 18:46:40.923 stardard cleo.log starts
03/10/2025 18:46:40.923 ...
03/10/2025 18:46:40.923 ... new game session
|-frame 12200
| ....
|-frame 12415
03/10/2025 18:46:40.923 ...
03/10/2025 18:46:40.923 standard cleo.log ends
```

then cleo.log will be in manageable size.


In case of multiple restarts, we can repeat the process for each session (file size will be 200Mb x Number of restarts); or keep just last session in the log, and ignore previous sessions.

**Comment by MiranDMC** [comment]
> FOR FULL LOG case (or always?)
> 
> Potentially, we can still log to _script_log.txt but at the end when we close the game and flush cleo.log, merge content of _script_log.txt with cleo.log.
> 
> so, in cleo.log you would have
> 
> ```
> 03/10/2025 18:46:40.923 stardard cleo.log starts
> 03/10/2025 18:46:40.923 ...
> 03/10/2025 18:46:40.923 ... new game session
> ## SCRIPT_LOG_GOES_HERE ##
> ```
> 
> then we open _script_log.txt and log/truncate content here, then when the session ends for whatever reason, we take its content and replace ## SCRIPT_LOG_GOES_HERE ## with it.
> 
> ```
> 03/10/2025 18:46:40.923 stardard cleo.log starts
> 03/10/2025 18:46:40.923 ...
> 03/10/2025 18:46:40.923 ... new game session
> |-frame 12200
> | ....
> |-frame 12415
> 03/10/2025 18:46:40.923 ...
> 03/10/2025 18:46:40.923 standard cleo.log ends
> ```
> 
> then cleo.log will be in manageable size.
> 
> In case of multiple restarts, we can repeat the process for each session (file size will be 200Mb x Number of restarts); or keep just last session in the log, and ignore previous sessions.

Sounds like over complicating. Logs can not be read in any way, the append to the back mode is used now.
You can keep pointer to internal buffer every time new a frame starts as variable.

**Comment by MiranDMC** [comment]
If you want adding script log to main cleo log in case of script crash it probably makes sense to just report last script, not entire frame.

**Comment by x87** [comment]
I guess you are right, let's not overthink it. I mostly care about crash log, we can just duplicate it in cleo.log, while keeping current logic in place. So for the most user reports, cleo.log alone should be sufficient.

For deeper issues, debugging you can also refer to script_ log with all frames/scripts

**Comment by MiranDMC** [comment]
This is third time my game crashes without any message, and log looks like this:
```
  |    {431994}   if
  |    {431998}       not 2@(1) == 1 // -> condition: false
  |    {432005} 
  ```
  Decompiled script does not contain anything suspicious there
 ```
 dm_tips_1505
{431994} if 
{431998}   2@ <> 1
{432005} goto_if_false @dm_tips_1663
```

**Comment by x87** [comment]
> This is third time my game crashes without any message, and log looks like this:
> 
> ```
>   |    {431994}   if
>   |    {431998}       not 2@(1) == 1 // -> condition: false
>   |    {432005} 
> ```

is this full log? what script could it be?

**Comment by MiranDMC** [comment]
> > This is third time my game crashes without any message, and log looks like this:
> > ```
> >   |    {431994}   if
> >   |    {431998}       not 2@(1) == 1 // -> condition: false
> >   |    {432005} 
> > ```
> 
> is this full log? what script could it be?

My DYOM Enhancer. Previously crashed in different place, so it does not look like script's fault.

**Comment by x87** [comment]
what's there at 432005? can you show source before and after?

it might be a script issue, but the log was not flushed completely, so you lost part of the content.

**Comment by MiranDMC** [comment]
> what's there at 432005? can you show source before and after?
> 
> it might be a script issue, but the log was not flushed completely, so you lost part of the content.

I do not know. In my version log was always flushed even on game crash. Looks like offset was printed but command name not. So if flushing works it is problem in logging itself.

**Comment by x87** [comment]
these are the changes that I made, I don't see anything related to flushing

```diff
diff --git a/cleo_plugins/DebugUtils/SA.DebugUtils.ini b/cleo_plugins/DebugUtils/SA.DebugUtils.ini
index 0affd20..2efe561 100644
--- a/cleo_plugins/DebugUtils/SA.DebugUtils.ini
+++ b/cleo_plugins/DebugUtils/SA.DebugUtils.ini
@@ -21,7 +21,7 @@ ColorSystem = "DDDDDDFF"
 
 
 [ScriptLog]
-Enabled = 1 ; log scripts execution into cleo\.cleo_script_log.xml file: 0 - never, 1 - on game crash, 2 - all the time
+Enabled = 1 ; log scripts execution into cleo\_cleo_script_log.txt file: 0 - never, 1 - on game crash, 2 - all the time
 MaxSize = 250 ; max size of log file in megabytes, after which it will be cleared. Set 0 to disable the limit
 OnlyCustomScripts = -1 ; log only Custom Scripts, skip main.scm: -1 - automatic, 0 - all, 1 - CS only
 OnlyDebugScripts = 0 ; log only scripts where debug_on command was used: 0 - all, 1 - debug mode only
diff --git a/cleo_plugins/DebugUtils/ScriptLog.cpp b/cleo_plugins/DebugUtils/ScriptLog.cpp
index 7eab23c..39df55b 100644
--- a/cleo_plugins/DebugUtils/ScriptLog.cpp
+++ b/cleo_plugins/DebugUtils/ScriptLog.cpp
@@ -21,8 +21,15 @@ ScriptLog::ScriptLog()
     assert(g_Instance == nullptr);
     g_Instance = this;
 
+    LoadConfig();
+
+    if (state == LoggingState::Disabled)
+    {
+        return;
+    }
+
     m_logFilePath = CLEO_GetGameDirectory();
-    m_logFilePath += "\\cleo\\.cleo_script_log.xml";
+    m_logFilePath += "\\cleo\\_cleo_script_log.txt";
     LogFileDelete();
 
     CLEO_RegisterCallback(eCallbackId::GameBegin, callbackGameBegin);
@@ -35,8 +42,6 @@ ScriptLog::ScriptLog()
     CLEO_RegisterCallback(eCallbackId::DrawingFinished, callbackDrawingFinished);
     CLEO_RegisterCallback(eCallbackId::MainWindowFocus, callbackMainWindowFocus);
 
-    LoadConfig();
-
     std::string path = CLEO_GetGameDirectory();
     path += "\\cleo\\.config\\sa.json";
     m_opcodeDatabase.LoadCommands(path.c_str());
@@ -54,6 +59,11 @@ ScriptLog::~ScriptLog()
 {
     // TODO: stop file writer thread
 
+    if (state == LoggingState::Disabled)
+    {
+        return;
+    }
+
     m_patchSetConditionResult.Apply(); // undo hook
 
     CLEO_UnregisterCallback(eCallbackId::GameBegin, callbackGameBegin);
@@ -118,17 +128,10 @@ void ScriptLog::SetCurrScript(CLEO::CRunningScript* script)
     // close previous script's log block
     if (m_currScript != nullptr && script != m_currScript && state != LoggingState::Disabled && m_currScriptLogging)
     {
-        if (m_currScriptCommandCount > 0)
-        {
-            if (m_processingGame) LogAppend(Block_Indent);
-            LogAppend(Block_Indent);
-            LogAppend("Executed in ");
-            LogAppendNum(size_t(clock() - m_currScriptStartTime) * 1000 / CLOCKS_PER_SEC);
-            LogAppend(" ms\n");
-        }
-
-        if (m_processingGame) LogAppend(Block_Indent);
-        LogAppend("</script>\n");
+        LogAppend("  |-- Executed in ");
+        LogAppendNum(size_t(clock() - m_currScriptStartTime) * 1000 / CLOCKS_PER_SEC);
+        LogAppend(" ms");
+        LogLine("  |");
     }
 
     // find index of this script in active scripts queue
@@ -205,54 +208,63 @@ void ScriptLog::SetCurrScript(CLEO::CRunningScript* script)
             filename = "?";
         }
 
-        LogAppend('\n');
-        if (m_processingGame) LogAppend(Block_Indent);
-        LogAppend("<script idx='");
+        LogNewLine();
+        LogAppend(" -|-- Script ");
         LogAppendNum(scriptIdx);
-
-        LogAppend("' name='");
-        LogAppend(script->GetName());
-
-        LogAppend("' file='");
+        LogAppend(": ");
         LogAppend(filename);
-        LogAppend("'");
 
-        if (script->IsCustom()) LogAppend(" custom='true'");
-        if (script->IsMission()) LogAppend(" mission='true'");
-        if (CLEO_GetScriptDebugMode(script)) LogAppend(" debug='true'");
+        // Add flags in parentheses
+        bool hasFlags = false;
+        if (script->IsCustom() || script->IsMission() || CLEO_GetScriptDebugMode(script))
+        {
+            LogAppend(" - ");
+            if (script->IsCustom())
+            {
+                LogAppend("custom");
+                hasFlags = true;
+            }
+            if (script->IsMission())
+            {
+                if (hasFlags) LogAppend(", ");
+                LogAppend("mission");
+                hasFlags = true;
+            }
+            if (CLEO_GetScriptDebugMode(script))
+            {
+                if (hasFlags) LogAppend(", ");
+                LogAppend("debug");
+                hasFlags = true;
+            }
+        }
 
         auto ver = CLEO_GetScriptVersion(script);
         if (ver != eCLEO_Version::CLEO_VER_CUR)
         {
-            LogAppend(" compat='");
+            LogAppend(hasFlags ? ", " : " - ");
             switch (ver)
             {
             case eCLEO_Version::CLEO_VER_3:
-                LogAppend("CLEO3");
+                LogAppend("CLEO3 compat mode");
                 break;
             case eCLEO_Version::CLEO_VER_4:
-                LogAppend("CLEO4");
+                LogAppend("CLEO4 compat mode");
                 break;
             case eCLEO_Version::CLEO_VER_5:
-                LogAppend("CLEO5");
+                LogAppend("CLEO5 compat mode");
                 break;
             default:
                 LogAppendHex(ver);
                 break;
             }
-            LogAppend("'");
         }
 
-        LogAppend(">");
-
         // call stack info
         auto cleoStack = CLEO_GetCleoCallStackSize(script);
         if (cleoStack || script->SP)
         {
-            LogAppend('\n');
-            if (m_processingGame) LogAppend(Block_Indent);
-            LogAppend(Block_Indent);
-            LogAppend("Call Stacks depth - cleo_call: ");
+            LogNewLine();
+            LogAppend(" -|   Call Stacks - cleo_call: ");
             LogAppendNum(cleoStack);
             LogAppend(", gosub: ");
             LogAppendNum(script->SP);
@@ -260,7 +272,7 @@ void ScriptLog::SetCurrScript(CLEO::CRunningScript* script)
             bool savingEnabled = !script->IsCustom() || false; // TODO: check CLEO save enabled for custom script
             if (savingEnabled && cleoStack)
             {
-                LogAppend(" \\ BUG: Scrip saving enabled. Saving during cleo_call would result in errors!");
+                LogAppend(" \\ BUG: Script saving enabled. Saving during cleo_call would result in errors!");
             }
 
             bool wastedBustedCheck = script->IsMission() && script->bWastedBustedCheck;
@@ -283,15 +295,13 @@ void ScriptLog::SetCurrScript(CLEO::CRunningScript* script)
         // 'wait' command in progress?
         if (script->WakeTime > CTimer::m_snTimeInMilliseconds)
         {
-            LogAppend('\n');
-            if (m_processingGame) LogAppend(Block_Indent);
-            LogAppend(Block_Indent);
-            LogAppend("Sleeping for ");
+            LogNewLine();
+            LogAppend("  |   Sleeping for ");
             LogAppendNum(script->WakeTime - CTimer::m_snTimeInMilliseconds);
             LogAppend(" ms more");
         }
 
-        LogAppend('\n');
+        LogNewLine();
     }
 
     // update/reset script stats
@@ -307,8 +317,8 @@ void ScriptLog::SetCurrScript(CLEO::CRunningScript* script)
 void ScriptLog::LogLine(const std::string_view& str)
 {
     // TODO: thread lock
-    m_logBuffer += '\n';
-    m_logBuffer += str;
+    LogNewLine();
+    LogAppend(str);
     // TODO: thread unlock
 }
 
@@ -379,6 +389,17 @@ inline void ScriptLog::LogAppendSpace()
     // TODO: thread unlock
 }
 
+inline void ScriptLog::LogSeparator()
+{
+    LogAppend("------------------------------------------------");
+    LogNewLine();
+}
+
+inline void ScriptLog::LogNewLine()
+{
+    LogAppend('\n');
+}
+
 bool ScriptLog::LogAppendScriptParam(
     CLEO::CRunningScript* script, const OpcodeInfoDatabase::Command* command, size_t paramIdx, bool logName,
     bool logVariable, bool logValue
@@ -678,27 +699,16 @@ void ScriptLog::LogFileDelete()
 
 void __fastcall ScriptLog::HOOK_SetConditionResult(CLEO::CRunningScript* script, int dummy, bool state)
 {
-    if (script->NotFlag) state = !state;
-
     g_Instance->m_conditionResultUpdated = true;
-    g_Instance->m_conditionResultValue   = state;
-
-    // restoring and calling orignal function code is more performance costly than reimplementing it here
-
-    if (script->LogicalOp == eLogicalOperation::NONE)
-    {
-        script->bCondResult = state;
-    }
-    else if (script->LogicalOp >= eLogicalOperation::ANDS_1 && script->LogicalOp < eLogicalOperation::AND_END)
-    {
-        script->bCondResult &= state;
-        --script->LogicalOp;
-    }
-    else if (script->LogicalOp >= eLogicalOperation::ORS_1 && script->LogicalOp < eLogicalOperation::OR_END)
-    {
-        script->bCondResult |= state;
-        --script->LogicalOp;
-    }
+    g_Instance->m_conditionResultValue   = script->NotFlag ? !state : state;
+
+    // restore original function code
+    g_Instance->m_patchSetConditionResult.Apply();
+    // call original function
+    ((::CRunningScript*)script)->UpdateCompareFlag(state);
+    // reinstall our hook
+    g_Instance->m_patchSetConditionResult =
+        MemPatchJump(gaddrof(::CRunningScript::UpdateCompareFlag), &HOOK_SetConditionResult);
 }
 
 void ScriptLog::OnGameBegin(DWORD saveSlot)
@@ -718,6 +728,10 @@ void ScriptLog::OnGameBegin(DWORD saveSlot)
         t.wMilliseconds
     );
 
+    LogSeparator();
+    LogAppend("  Game started at: ");
+    LogAppend(timeStamp);
+
     if (CGame::bMissionPackGame)
     {
         // find name of the mission pack
@@ -730,12 +744,11 @@ void ScriptLog::OnGameBegin(DWORD saveSlot)
                 break;
             }
         }
-
-        LogFormattedLine(
-            "<newGameSession mPack='%d' mPackName='%s' time='%s'/>", FrontEndMenuManager.m_nSelectedMissionPack,
-            packName ? packName : "???", timeStamp
-        );
-
+        LogLine("  Mission Pack: ");
+        LogAppendNum(FrontEndMenuManager.m_nSelectedMissionPack);
+        LogLine("  Mission Pack Name: ");
+        LogAppend(packName ? packName : "???");
+        LogNewLine();
         m_customMain = true;
     }
     else
@@ -751,50 +764,20 @@ void ScriptLog::OnGameBegin(DWORD saveSlot)
 
         if (saveSlot != -1)
         {
-            LogFormattedLine(
-                "<newGameSession saveSlot='%d' mainScript='%s' time='%s'/>",
-                saveSlot + 1, // 1-based index
-                m_customMain ? "modified" : "original", timeStamp
-            );
-        }
-        else
-        {
-            LogFormattedLine(
-                "<newGameSession mainScript='%s' time='%s'/>", m_customMain ? "modified" : "original", timeStamp
-            );
+            LogLine("  Save Slot: ");
+            LogAppendNum(saveSlot + 1); // 1-based index
         }
+        LogLine("  Main Script: ");
+        LogAppend(m_customMain ? "modified" : "original");
+        LogNewLine();
     }
-
-    LogAppend('\n'); // separator
+    LogSeparator();
 }
 
 void ScriptLog::OnGameProcessBefore()
 {
     if (!CTimer::m_UserPause && !CTimer::m_CodePause) m_processingGame = true;
 
-    // 'CLOG' cheat
-    if (_strnicmp(CCheat::m_CheatString, "golc", 4) == 0) // reversed order
-    {
-        CCheat::m_CheatString[0] = '\0'; // consume the cheat
-
-        state = (state == LoggingState::Full) ? LoggingState::OnCrash : LoggingState::Full; // toggle
-        if (state == LoggingState::Full) LoadConfig(true); // refresh config from ini file
-
-        if (state == LoggingState::Full)
-        {
-            CHud::SetHelpMessage("CLEO script log: ~g~~h~~h~~h~ON~s~", true, false, false);
-            LogLine("Log: ON\n");
-        }
-        else
-        {
-            CHud::SetHelpMessage("CLEO script log: ~r~~h~~h~~h~OFF~s~", true, false, false);
-            LogLine("Log: OFF\n");
-            LogWriteFile(); // flush
-        }
-    }
-
-    if (state == LoggingState::Disabled) return;
-
     // count active scripts
     if (m_processingGame)
     {
@@ -806,11 +789,12 @@ void ScriptLog::OnGameProcessBefore()
             next = next->m_pNext;
         }
 
-        LogAppend("\n<gameProcess frame='");
+        LogNewLine();
+        LogAppend("--|-- Frame ");
         LogAppendNum(CTimer::m_FrameCounter);
-        LogAppend("' activeScripts='");
+        LogAppend(" - Active Scripts: ");
         LogAppendNum(scriptCount);
-        LogAppend("'>");
+        LogLine("  |");
     }
 }
 
@@ -818,11 +802,6 @@ void ScriptLog::OnGameProcessAfter()
 {
     SetCurrScript(nullptr);
 
-    if (state != LoggingState::Disabled)
-    {
-        if (m_processingGame) LogAppend("</gameProcess>\n");
-    }
-
     m_processingGame = false;
 }
 
@@ -839,6 +818,15 @@ void ScriptLog::OnScriptProcessAfter(CLEO::CRunningScript* script)
 
 OpcodeResult ScriptLog::OnScriptOpcodeProcessBefore(CLEO::CRunningScript* script, DWORD opcode)
 {
+    // late initialization
+    if (!m_initialized)
+    {
+        m_patchSetConditionResult =
+            MemPatchJump(gaddrof(::CRunningScript::UpdateCompareFlag), &HOOK_SetConditionResult);
+
+        m_initialized = true;
+    }
+
     SetCurrScript(script);
     m_currScriptCommandCount++;
 
@@ -852,8 +840,7 @@ OpcodeResult ScriptLog::OnScriptOpcodeProcessBefore(CLEO::CRunningScript* script
 
     auto oriIP = script->CurrentIP;
 
-    if (m_processingGame) LogAppend(Block_Indent); // game processing block indentation
-    if (m_currScript) LogAppend(Block_Indent);     // script processing block indentation
+    LogAppend("  |   "); // script content indentation
 
     // script offset
     if (logOffsets)
@@ -1026,7 +1013,7 @@ CLEO::OpcodeResult ScriptLog::OnScriptOpcodeProcessAfter(
     auto command = m_opcodeDatabase.GetCommand((uint16_t)opcode);
     if (!command)
     {
-        LogAppend('\n');
+        LogNewLine();
         return result;
     }
 
@@ -1095,22 +1082,13 @@ CLEO::OpcodeResult ScriptLog::OnScriptOpcodeProcessAfter(
         LogAppend("BUG?: Custom Script writes global variable");
     }
 
-    LogAppend('\n');
+    LogNewLine();
 
     return result;
 }
 
 void ScriptLog::OnDrawingFinished()
 {
-    // late initialization
-    if (!m_initialized)
-    {
-        m_patchSetConditionResult =
-            MemPatchJump(gaddrof(::CRunningScript::UpdateCompareFlag), &HOOK_SetConditionResult);
-
-        m_initialized = true;
-    }
-
     // this should be done just at the end of scripts processing
     // but PluginSDK, SAMP etc. call single scripts/callbacks outside of the processing queue
     // make sure current script does not persists to next render frame
diff --git a/cleo_plugins/DebugUtils/ScriptLog.h b/cleo_plugins/DebugUtils/ScriptLog.h
index b4ff59c..1640f64 100644
--- a/cleo_plugins/DebugUtils/ScriptLog.h
+++ b/cleo_plugins/DebugUtils/ScriptLog.h
@@ -35,7 +35,6 @@ class ScriptLog
 
   private:
     static constexpr size_t Initial_Buff_Size = 16 * 1024 * 1024; // 16 MB
-    const char* Block_Indent                  = "    ";
     const char* Script_Indent                 = "    ";
 
     bool m_initialized = false;
@@ -64,6 +63,8 @@ class ScriptLog
     inline void LogAppendHex(int number, int padLen = 0);
     inline void LogAppendFloat(float number, int padLen = 0);
     inline void LogAppendSpace(); // add white char separator at end of the line if not present
+    inline void LogSeparator();
+    inline void LogNewLine();
     bool LogAppendScriptParam(
         CLEO::CRunningScript* script, const OpcodeInfoDatabase::Command* command, size_t paramIdx, bool logName,
         bool logVariable, bool logValue

```

**Comment by x87** [comment]
what log config do you have?

**Comment by MiranDMC** [comment]
> what log config do you have?

I had default + full logging enabled. I switched back to CLEO 5.1.0 and so far no crashes.

**Comment by x87** [comment]
> > what log config do you have?
> 
> I had default + full logging enabled. I switched back to CLEO 5.1.0 and so far no crashes.

Could be anything. We have many changes between 5.1 and 5.2

How consistent it was? Did you do anything or it was just random? Scrlog or CrashInfo?
Any chance for running under debugger to see where it fails?

**Comment by MiranDMC** [comment]
> > > what log config do you have?
> > 
> > 
> > I had default + full logging enabled. I switched back to CLEO 5.1.0 and so far no crashes.
> 
> Could be anything. We have many changes between 5.1 and 5.2
> 
> How consistent it was? Did you do anything or it was just random? Scrlog or CrashInfo? Any chance for running under debugger to see where it fails?

3 times one day. Maybe debug builds would show something. Or maybe not. When I was investigating the weird crashes before it was same behavior: game app just disappearing.

**Comment by x87** [comment]
Do you have CrashInfo?

**Comment by MiranDMC** [comment]
No. Default option in Crash Info window is "force close", which kills game without giving CLEO chance to flush the logs.

**Comment by x87** [comment]
Ok, but it would show where it crashes. I thought we don't know where and why it happens

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 6]
```diff
@@ -76,6 +76,11 @@ ScriptLog::~ScriptLog()
     CLEO_UnregisterCallback(eCallbackId::DrawingFinished, callbackDrawingFinished);
     CLEO_UnregisterCallback(eCallbackId::MainWindowFocus, callbackMainWindowFocus);
 
+    if (state == LoggingState::OnCrash && !m_logBuffer.empty())
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp:79]: It will be misleading if the crashing script is logging is disabled (crashing main when logging only custom, or logging only scripts in debug mode). It can be solved by storing pointer to current end of m_logBuffer whenever new script processing starts. It should be nulled if the script is not logged and when m_logBuffer is flushed.

Why only OnCrash? Even single frame log will be really long as there is multiple scripts executed every frame. Not to mention if somebody has RZL Trainer. Cleo.log can become to fat to post without packing.

File: cleo_plugins/DebugUtils/ScriptLog.cpp [hunk 7]
```diff
@@ -76,6 +76,11 @@ ScriptLog::~ScriptLog()
...
+    {
+        CLEO_Log(eLogLevel::Debug, m_logBuffer.c_str());
```
Comment (MiranDMC) [inline cleo_plugins/DebugUtils/ScriptLog.cpp]: Should be eLogLevel::Default. It is not debug message, also there is no point trying to print it one the screen.

File: cleo_plugins/DebugUtils/ScriptLog.cpp (hunk 6 above)
Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: Not sure what's the concern here. Are these arguments not apply to the _script_log.txt itself? We just copy its content to cleo.log

Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: Crash log should always log the last script, irrespective of settings, otherwise it's useless.

Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: Crash log contains entire last frame, not just last script.
There is no way to know the script is about to crash in advance so it is difficult to enable logging if configured otherwise.

Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: Yes, which is why the logging should have been designed a bit different. You always collect info about current script (in case it crashes and you want to log it), but you may not add it to the log file if it completed successfully and it does not match the filters.

Comment (MiranDMC) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: It is slow enough already. If somebody disabled logging for the script he should be informed about it.
Keeping pointer to the script's log start or nullptr would solve that.
Then the cleo log can contain info that "processing of script X was interrupted" and log or info about lack of log...

Comment (x87) [reply cleo_plugins/DebugUtils/ScriptLog.cpp:79]: this should be part of default _cleo_script.log

**Review by x87 — COMMENTED** [review]
my changes: https://github.com/cleolibrary/CLEO5/pull/454/commits/46d7d8d1cb7061176c89d42573ca57b59599f4e6
* switched from xml to simple txt format
   * WHY: xml format has specific structure and more verbose, difficult to view using default programs
* renamed .cleo_script_log.xml to _cleo_script.log
  * WHY: see above, format changed from xml to txt, .log is more traditional, no conflicts with txt script sources in CLEO folder, . does not let the file to be attached to github discussions
* hooks are not installed if logging is disabled
  * WHY: have a way to completely ignore plugin when not needed (e.g conflicts with other libraries, or performance degradation)  
* removed CLOG cheat
  * WHY: very narrow use case, possible conflicts with existing cheats, requires an additional hook to track keypresses. Can be replicated with TEST_CHEAT + DEBUG_ON commands in the code.
* copy content of _cleo_script.log to cleo.log on crash
  * WHY: easier issue reporting, user will attach one file with all info, a full log can be requested/provided additionally
* the condition hook is reinstalled to call the original function (and possibly other hooks)
  * WHY: other libraries (notably SCRLog) also hook this function, need to let them work.
* fixed condition result not being tracked when imfast plugin is used

**Comment by x87** [comment]
@MiranDMC I think we can merge this to master and get some feedback. Any additional ideas can be implemented later, it does not have to be perfect.
