### PR TITLE
Fix paths validation

### LINKED ISSUE #528: Path traversal in FilepathIsSafe function
No | Issue | Description | Example Bypass | Severity
-- | -- | -- | -- | -- |
1 | Absolute path escape | Absolute paths are never restricted to game/user directories. | C:\Windows\system.ini | Critical
2 | Broken sandbox logic | If path is outside allowed dirs, it is rejected only if it starts with "..". Most external paths pass. | D:\Other\file.txt | Critical
3 | Prefix collision | StringStartsWith() allows sibling directories with similar prefixes. | C:\Games\GTABackup\evil.txt when game dir is C:\Games\GTA | High
4 | No canonicalization | Absolute paths are not normalized before validation. Traversal remains possible. | C:\Games\GTA\..\..\Windows\file.txt | High
5 | Weak traversal check | Only checks if string starts with ".." — misses embedded traversal. | subdir\..\..\Windows | High
6 | UNC/device paths allowed | Network paths and device paths are not rejected. | \\\\Server\share\file.txt, \\\\.\PhysicalDrive0 | Medium
7 | Boundary not enforced | No directory component comparison — only string comparison. | Partial path match | High

### PR DESCRIPTION
**Pull request by x87**
Fixes #528

### CODE REVIEW

File: cleo_sdk/CLEO_Utils.h [hunk 1]
```diff
@@ -419,34 +419,29 @@ namespace CLEO
...
 
     // does normalized file path points inside game directories? (game root or user files)
+    // input path is expected to be absolute or relative to game directory
     static bool FilepathIsSafe(CLEO::CRunningScript* thread, const char* path)
     {
-        if (strchr(path, '%') != nullptr)
-        {
-            return false; // do not allow paths containing expandable variables
-        }
+        if (path == nullptr || strchr(path, '%') != nullptr) return false;
```
Comment (MiranDMC) [inline cleo_sdk/CLEO_Utils.h]: How is removal of comment helpful? Now reader will wonder what `%` is doing here.

File: source/CCustomOpcodeSystem.cpp [hunk 2]
```diff
@@ -877,9 +877,9 @@ namespace CLEO
     {
         OPCODE_READ_PARAM_STRING(path);
 
-        auto filename = reinterpret_cast<CCustomScript*>(thread)->ResolvePath(
-            path, DIR_CLEO
-        );                 // legacy: default search location is game\cleo directory
+        // convert path from relative to CLEO directory to relative to game directory
```
Comment (MiranDMC) [inline source/CCustomOpcodeSystem.cpp:880]: We can see WHAT it does. Previous comment was explaining WHY it does that.

File: cleo_sdk/CLEO_Utils.h (hunk 1 above)
Comment (x87) [reply cleo_sdk/CLEO_Utils.h]: Oh yeah, lets do this pointless nitpicking, when the function is completely broken. but we have COMMENTS instead!

File: tests/cleo_tests/cleo_tester.inc [hunk 3]
```diff
@@ -403,6 +402,26 @@ function assert_suffix(actual: string, expectedSuffix: string, ignoreCase: int)
     end
 end
 
+/// checks if code at label suspends current script
```
Comment (MiranDMC) [inline tests/cleo_tests/cleo_tester.inc:405]: One command under the label? 
Would in not be easier to just call the command and put always failing assert afterwards?

Comment (x87) [reply tests/cleo_tests/cleo_tester.inc:405]: What to do with message boxes?

Comment (MiranDMC) [reply tests/cleo_tests/cleo_tester.inc:405]: Hm right. Now it relies on fact foreign scripts have no hard validation.

Requirement for creating new labels is inconvenient. It would be nicer to have assert like "next command should fail", but I guess it is not possible as there is no guarantee IP would be properly advanced to next command. Some kind of assert region end marker would be needed.

Still the new script struct initialization looks very sparse. No variables, compat mode etc. Would not memcopy of host struct work?

Comment (x87) [reply tests/cleo_tests/cleo_tester.inc:405]: it's better than nothing and worked for this use case. definitely can be improved further, if needed.

Comment (MiranDMC) [reply tests/cleo_tests/cleo_tester.inc:405]: Compat mode seems rather crucial since test are automatically repeated with different one.

Ok it is not so easy since CCustomScript is not  trivially copy able.

Comment (x87) [reply tests/cleo_tests/cleo_tester.inc:405]: > Compat mode seems rather crucial since test are automatically repeated with different one.

Um, what's your concern with compat mode?

Comment (MiranDMC) [reply tests/cleo_tests/cleo_tester.inc:405]: New script will run in compact mode same as configured for main.scm. 
It works in current use case, but currently tested commands have no legacy specific behavior.

File: cleo_sdk/CLEO_Utils.h [hunk 4]
```diff
@@ -418,35 +431,36 @@ namespace CLEO
...
         {
-            absolute = CLEO_GetScriptWorkDir(thread);
-            if (!absolute.empty())
-            {
-                absolute += '\\';
-                absolute += path;
-                FilepathNormalize(absolute);
-                path = absolute.c_str();
-            }
+            resolved = CLEO_GetGameDirectory();
```
Comment (MiranDMC) [inline cleo_sdk/CLEO_Utils.h:445]: Why script's work dir is ignored, instead game dir is hard coded?

Comment (x87) [reply cleo_sdk/CLEO_Utils.h:445]: yea. this is why I updated all comments, CLEO_ResolvePath already takes care of script directory. When we enter FilepathIsSafe, the path is either absolute, or relative to game root.

Comment (MiranDMC) [reply cleo_sdk/CLEO_Utils.h:445]: That's why I do not like it. It alerts everything around for no reason. It is supposed to be simple validation check, but now it dictates how logic outside of it is supposed to work. 
Comment will not stop anybody to use it wrongly.

Comment (x87) [reply cleo_sdk/CLEO_Utils.h:445]: The only other alternative is to call CLEO_ResolvePath at the start, but it is already done in the macros.

Comment (MiranDMC) [reply cleo_sdk/CLEO_Utils.h:445]: Ok I see. This is almost like day 1 where I wanted to always operate on absolute paths. "relative game root" is kind of absolute path forced by ModLoader.

Comment (MiranDMC) [reply cleo_sdk/CLEO_Utils.h:445]: Ok the only location it is used is inside the macro reading input path param.

File: source/CCustomOpcodeSystem.cpp (hunk 2 above)
Comment (MiranDMC) [reply source/CCustomOpcodeSystem.cpp:880]: Comment still does not clearly inform that default scripts search location is cleo directory, unless absolute path is provided.

File: source/CCustomOpcodeSystem.cpp [hunk 5]
```diff
@@ -1013,11 +1013,8 @@ namespace CLEO
             auto strExport = std::string_view(moduleTxt.data(), pos);
             auto strModule = std::string_view(moduleTxt.data() + pos + 1);
 
-            // get module's file absolute path
-            auto modulePath = std::string(strModule);
-            modulePath      = reinterpret_cast<CCustomScript*>(thread)->ResolvePath(
-                modulePath.c_str(), DIR_SCRIPT
-            ); // by default search relative to current script location
+            // convert path from relative to script directory to relative to game directory
```
Comment (MiranDMC) [inline source/CCustomOpcodeSystem.cpp:1016]: Comment looses meaning. It just paraphrases code line instead of providing additional context information. Did AI generated it?

Why not just reuse original comments of that logic block? `// get module's file absolute path (by default search relative to current script location)`

Comment (x87) [reply source/CCustomOpcodeSystem.cpp:1016]: Because ResolvePath does not make path absolute. Relative path remains relative. Old comment was misleading

File: source/CCustomOpcodeSystem.cpp (hunk 2 above)
Comment (x87) [reply source/CCustomOpcodeSystem.cpp:880]: It depends on the reader comprehension

File: source/CCustomOpcodeSystem.cpp (hunk 5 above)
Comment (MiranDMC) [reply source/CCustomOpcodeSystem.cpp:1016]: Still the most important nuance of these comments was stating the fact there are hard coded default search locations.
Now we have tricky code explained with tricky comment. During next round of path related fixes it will be "ironed out" as it was not explained clearly enough.

Comment (x87) [reply source/CCustomOpcodeSystem.cpp:1016]: Ok, it's just some white noise now. I assume you agree with the rest of code changes and just have a lot of time to spare.
