### PR TITLE
Fix game crash on invalid format string

### LINKED ISSUE #478: String format sequence crashing the game
It is possible to crash the game by providing incomplete number format sequence like:
```
debug_on
trace "%0.0" 1.0
```
The **f** character is missing at end of formatting text.

### PR DESCRIPTION
**Pull request by x87**
Fixes #478 

- support uppercase modifiers (%D %C %S) in addition to already supported %P
- providing nullptr for format string now errors instead of returning an empty string (it crashed in CLEO 4)
- CLEO_ReadParamsFormatted now consistently handles small buffer size (see unit tests)
- fix crash on calling sprintf with invalid format specifiers
- add support for `hh` length modifier, which represents a signed char (-128..127) (e.g. "%hhd") in addition to already supported `h` and `l`
- `%p` formats the address in lowercase, `%P` formats the address in uppercase
- simplify code
- add unit tests

## CLEO 4.4.4 Behavior

```
{0AD1:} print_formatted_now {format} "hi %D" {time} 5000 {args} 100 // "hi D"
{0AD1:} print_formatted_now {format} "hi %C" {time} 5000 {args} 0x41 // "hi A"
{0AD1:} print_formatted_now {format} "hi %S" {time} 5000 {args} 'world' // Game crash
{0AD1:} print_formatted_now {format} "hi %F" {time} 5000 {args} 42.5 // "hi 42.50000"
{0AD1:} print_formatted_now {format} "hi %p" {time} 5000 {args} 0x123ABC // "hi 00123ABC"
{0AD1:} print_formatted_now {format} "hi %P" {time} 5000 {args} 0x123ABC // "hi 00123ABC"
{0AD1:} print_formatted_now {format} 0 {time} 5000 // Game crash
```

Note: printf supports both %c and %C, crashes on %S and ignores %D. Pretty inconsistent

## New CLEO 5.3 Behavior
```
{0AD1:} print_formatted_now {format} "hi %D" {time} 5000 {args} 100 // "hi 100"
{0AD1:} print_formatted_now {format} "hi %S" {time} 5000 {args} 'world' // "hi world"
{0AD1:} print_formatted_now {format} "hi %p" {time} 5000 {args} 0x123ABC // "hi 00123abc"
{0AD1:} print_formatted_now {format} 0 {time} 5000 // Script suspended
```

### CODE REVIEW

File: source/CCustomOpcodeSystem.cpp [hunk 1]
```diff
@@ -1,1365 +1,1355 @@
...
-    // perform 'sprintf'-operation for parameters, passed through SCM
-    int ReadFormattedString(CRunningScript* thread, char* outputStr, DWORD len, const char* format)
-    {
-        unsigned int written = 0;
-        const char* iter     = format;
-        char* outIter        = outputStr;
-        char bufa[MAX_STR_LEN + 1], fmtbufa[64], *fmta;
-
-        // invalid input arguments
-        if (outputStr == nullptr || len == 0)
```
Comment (x87) [inline source/CCustomOpcodeSystem.cpp:376]: The SDK wrapper ensures these are never empty.

File: source/CCustomOpcodeSystem.cpp [hunk 2]
```diff
@@ -1,1365 +1,1355 @@
...
-        if (thread->PeekDataType() != DT_END)
-        {
-            LOG_WARNING(
-                thread, "More arguments than tokens in format string in script %s", ScriptInfoStr(thread).c_str()
-            );
-        }
-        SkipUnusedVarArgs(thread); // skip terminator too
-
-        outputStr[written] = '\0';
-        return (int)written;
```
Comment (x87) [inline source/CCustomOpcodeSystem.cpp:611]: we are not using this value, so changing to return the pointer instead

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt [hunk 3]
```diff
@@ -0,0 +1,165 @@
+{$CLEO .s}
+{$INCLUDE_ONCE ../cleo_tester.inc}
+
+script_name 'SDK@31'
+test("SDK: CLEO_ReadParamsFormatted", tests)
```
Comment (x87) [inline tests/cleo_tests/SDK/ReadParamsFormatted.txt:5]: testing via SDK because opcodes throw an error and stop the script

File: source/CCustomOpcodeSystem.cpp [hunk 4]
```diff
@@ -1,1365 +1,1355 @@
-#include "stdafx.h"
```
Comment (x87) [inline source/CCustomOpcodeSystem.cpp:1]: I'm not sure what happened here. View with ignore whitespace
https://github.com/cleolibrary/CLEO5/pull/485/changes?w=1

Comment (x87) [reply source/CCustomOpcodeSystem.cpp:1]: looks like my Git converted line endings

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt [hunk 5]
```diff
@@ -0,0 +1,248 @@
...
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock11_ptr, buf, 2)
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock14_valid_str_ptr, buf, 2)
+        assert_eq(formatted, 0)
+    end
+    
+    function test7
+        int formatted = GetFormattedString(@mock16_nullfmt) // trace 0 {args} 0
+        assert_eqs(formatted, "")
```
Comment (x87) [inline tests/cleo_tests/SDK/ReadParamsFormatted.txt]: Unsure about this. feel like this should be an error instead

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt [hunk 6]
```diff
@@ -0,0 +1,248 @@
...
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock9_pct, buf, 2)
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock10_long, buf, 2)
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock11_ptr, buf, 2)
+        assert_eq(formatted, 0)
+        formatted = GetFormattedStringWithBuf(@mock14_valid_str_ptr, buf, 2)
+        assert_eq(formatted, 0)
+    end
```
Comment (x87) [inline tests/cleo_tests/SDK/ReadParamsFormatted.txt]: So, buf size 1 is OK, but buf size 2 is ERROR? Surprising result. In both case they can't fit the output completely.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: For reference, CLEO4 crashes if format string is nullptr.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 6 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: No way to reproduce buffer overflow in CLEO4 as public API (format opcodes use static buffers), but the game crashes with 
```
print_formatted_now {format} "%s" {time} 5000 "..." // line with 130+ characters
```

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: Argument validation does not let 0 as a string argument. But without it, `trace 0` does nothing and `trace 0 0` creates a warning on more tokens, just like `trace "" 0`

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 6 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: OK, buf should also include a null-terminator, so buf size 1 can only work with an empty format string. Anything else should throw an error (not enough space) like buf size 2 does

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: I'm more inclined to treat nullptr format string as an error. 

1. argument validation already rejects 0 as a invalid input, so it should error out downstream
2. c++ printf errors on nullptr format
3. empty string exists for "no format" case (trace "")

Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: Changed to error.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 6 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: Now handles small buffer consistently

File: source/CCustomOpcodeSystem.cpp (hunk 1 above)
Comment (MiranDMC) [reply source/CCustomOpcodeSystem.cpp:376]: I see no gain in removal input arguments validation.
At any moment somebody can add another call outside that wrapper.

Saving few instructions vs making obvious for one analyzing that function the args are for sure valid at this point, plus saving potential future time wasted on troubleshooting.

**Comment by MiranDMC** [comment]
Please check if following script:
```
{$CLEO .cs}
nop

int value = 0x7F800000

debug_on
trace "hex lower %x" value
trace "hex upper %X" value

trace "float lower %f" value
trace "float upper %F" value

terminate_this_script
```
still produces same result:
image

Following that logic maybe **%S** should be converting the param to upper case?

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (MiranDMC) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: `string_format str = ""` is proper way to clear the string.

Should not `trace 0` produce same result as `trace "%s" 0` ?
Currently it prints `(INVALID_STR)`

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt [hunk 7]
```diff
@@ -0,0 +1,239 @@
...
+trace "" {args} 0
+
+:mock9_pct
+trace "percent %%"
+
+:mock10_long
+trace "large string %s" {args} "This is a very long string that should fit into the buffer without any issues."
+
+:mock11_ptr
+trace "pointer %p" {args} 0x12345678
```
Comment (MiranDMC) [inline tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: Should contain hex characters and verify if resulting case is correct (currently `%p` is producing uppercase)
Should contain value that does not produce full 8 character string. `%p` should padd with zeros to 8 characters

File: tests/cleo_tests/Text/0AD3.txt [hunk 8]
```diff
@@ -11,6 +11,7 @@ function tests
     it("should respect short string variable size", test2)
     it("should respect long string variable size", test3)
     it("should create long text", test4)
+    it("should support uppercase", test5)
```
Comment (MiranDMC) [inline tests/cleo_tests/Text/0AD3.txt:13]: Missing tests for upper and lower case verification of `%x` `%X` and `%f` `%F`

File: source/CCustomOpcodeSystem.cpp (hunk 1 above)
Comment (MiranDMC) [reply source/CCustomOpcodeSystem.cpp:376]: It can be done as early exit to not indent contents of entire function.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: You can't normally use `trace 0` because of string argument validation. It is already an error. 
I think trace 0 and trace "%s" 0 are fundamentally different (format string is required and must be provided)

Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: And this is SDK method and affects all formatting opcodes, not just trace. They all must provide the format string.

**Comment by x87** [comment]
> Following that logic maybe **%S** should be converting the param to upper case?

I was thinking about that too. Decided to leave it as is for now.
The main argument is that, if %S forces the argument to be uppercase, then %s should force lowercase, but that's not true.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 5 above)
Comment (MiranDMC) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt]: Ok then.

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 7 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: so both `%p` and `%P` produce uppercase hex
both `%x` and `%X` produce lowercase hex

this is quite inconsistent

Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: Changed %p/%x to return lowercase, %P %X - uppercase

File: tests/cleo_tests/Text/0AD3.txt (hunk 8 above)
Comment (x87) [reply tests/cleo_tests/Text/0AD3.txt:13]: added

File: tests/cleo_tests/SDK/ReadParamsFormatted.txt (hunk 7 above)
Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: It gives a bit of flexibility if you prefer one style over another without having to convert number to a string and lowercasing/uppercasing.

Technically it's a breaking change but I'd be very surprised if some script could depend on specific hex output

Comment (MiranDMC) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: **x** and **X** worked before as expected. **P** always produced upper case.

Comment (x87) [reply tests/cleo_tests/SDK/ReadParamsFormatted.txt:137]: OK, makes sense. What do you think of splitting %p and %P?
